package model

import ()

//Race holds data about races (including models)
type Race struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Male    string `json:"male"`
	Female  string `json:"female"`
	Neutral string `json:"neutral"`
}

var races = map[int64]*Race{
	1: &Race{
		ID:     1,
		Name:   "Human",
		Male:   "HUM",
		Female: "HUF",
	},
	2: &Race{
		ID:     2,
		Name:   "Barbarian",
		Male:   "BAM",
		Female: "BAF",
	},

	3: &Race{
		ID:     3,
		Name:   "Erudite",
		Male:   "ERM",
		Female: "ERF",
	},
	4: &Race{
		ID:     4,
		Name:   "Wood Elf",
		Male:   "ELM",
		Female: "ELF",
	},
	5: &Race{
		ID:     5,
		Name:   "High Elf",
		Male:   "HIM",
		Female: "HIF",
	},
	6: &Race{
		ID:     6,
		Name:   "Dark Elf",
		Male:   "DAM",
		Female: "DAF",
	},
	7: &Race{
		ID:     7,
		Name:   "Half Elf",
		Male:   "HAM",
		Female: "HAF",
	},
	8: &Race{
		ID:     8,
		Name:   "Dwarf",
		Male:   "DWM",
		Female: "DWF",
	},
	9: &Race{
		ID:     9,
		Name:   "Troll",
		Male:   "TRM",
		Female: "TRF",
	},
	10: &Race{
		ID:     10,
		Name:   "Ogre",
		Male:   "OGM",
		Female: "OGF",
	},
	11: &Race{
		ID:     11,
		Name:   "Halfling",
		Male:   "HOM",
		Female: "HOF",
	},
	12: &Race{
		ID:     12,
		Name:   "Gnome",
		Male:   "GNM",
		Female: "GNF",
	},
	13: &Race{
		ID:      13,
		Name:    "Aviak",
		Neutral: "AVI",
	},
	14: &Race{
		ID:      14,
		Name:    "Werewolf",
		Neutral: "WER",
	},
	15: &Race{
		ID:     15,
		Name:   "Brownie",
		Male:   "BRM",
		Female: "BRF",
	},
	16: &Race{
		ID:      16,
		Name:    "Centaur",
		Male:    "CEM",
		Female:  "CEF",
		Neutral: "CEN",
	},
	17: &Race{
		ID:      17,
		Name:    "Golem",
		Male:    "GOM",
		Female:  "GOF",
		Neutral: "GOL",
	},
	18: &Race{
		ID:      18,
		Name:    "Giant",
		Neutral: "GIA",
	},
	19: &Race{
		ID:      19,
		Name:    "Trakanon",
		Neutral: "TRK",
	},
	20: &Race{
		ID:      20,
		Name:    "Venril Sathir",
		Neutral: "VST",
	},
	21: &Race{
		ID:      21,
		Name:    "Evil Eye",
		Neutral: "BEH",
	},
	22: &Race{
		ID:      22,
		Name:    "Beetle",
		Neutral: "BET",
	},
	23: &Race{
		ID:     23,
		Name:   "Kerran",
		Male:   "CPM",
		Female: "CPF",
	},
	24: &Race{
		ID:      24,
		Name:    "Fish",
		Neutral: "FIS",
	},

	25: &Race{
		ID:     25,
		Name:   "Fairy",
		Male:   "FAM",
		Female: "FAF",
	},
	26: &Race{
		ID:      26,
		Name:    "Froglok",
		Neutral: "FRO",
	},
	27: &Race{
		ID:      27,
		Name:    "Froglok",
		Neutral: "FRG",
	},
	28: &Race{
		ID:      28,
		Name:    "Fungusman",
		Neutral: "FUN",
	},
	29: &Race{
		ID:      29,
		Name:    "Gargoyle",
		Male:    "GAM",
		Neutral: "GAR",
	},
	30: &Race{
		ID:      30,
		Name:    "Gasbag",
		Neutral: "BEH",
	},
	31: &Race{
		ID:      31,
		Name:    "Gelatinous Cube",
		Neutral: "CUB",
	},
	32: &Race{
		ID:     32,
		Name:   "Ghost",
		Male:   "GHM",
		Female: "GHF",
	},
	33: &Race{
		ID:      33,
		Name:    "Ghoul",
		Neutral: "GHU",
	},
	34: &Race{
		ID:      34,
		Name:    "Bat",
		Neutral: "BAT",
	},
	36: &Race{
		ID:      36,
		Name:    "Rat",
		Neutral: "RAT",
	},
	37: &Race{
		ID:      37,
		Name:    "Snake",
		Neutral: "SNA",
	},
	38: &Race{
		ID:      38,
		Name:    "Spider",
		Neutral: "SPI",
	},
	39: &Race{
		ID:      39,
		Name:    "Gnoll",
		Neutral: "GNN",
	},
	40: &Race{
		ID:      40,
		Name:    "Goblin",
		Neutral: "GOB",
	},
	41: &Race{
		ID:      41,
		Name:    "Gorilla",
		Neutral: "GOR",
	},
	42: &Race{
		ID:      42,
		Name:    "Wolf",
		Male:    "WOM",
		Female:  "WOF",
		Neutral: "WOL",
	},
	43: &Race{
		ID:      43,
		Name:    "Bear",
		Neutral: "BEA",
	},
	44: &Race{
		ID:     44,
		Name:   "Guard",
		Male:   "FPM",
		Female: "FPF",
	},
	45: &Race{
		ID:      45,
		Name:    "Demi Lich",
		Neutral: "DML",
	},
	46: &Race{
		ID:      46,
		Name:    "Imp",
		Neutral: "IMP",
	},
	47: &Race{
		ID:      47,
		Name:    "Griffin",
		Neutral: "GRI",
	},
	48: &Race{
		ID:      48,
		Name:    "Kobold",
		Neutral: "KOB",
	},
	49: &Race{
		ID:      49,
		Name:    "Dragon",
		Neutral: "DRA",
	},
	50: &Race{
		ID:     50,
		Name:   "Lion",
		Male:   "LIM",
		Female: "LIF",
	},
	51: &Race{
		ID:      51,
		Name:    "Lizard Man",
		Neutral: "LIZ",
	},
	52: &Race{
		ID:     52,
		Name:   "Mimic",
		Male:   "MIM",
		Female: "MIF",
	},
	53: &Race{
		ID:      53,
		Name:    "Minotaur",
		Neutral: "MIN",
	},
	54: &Race{
		ID:      54,
		Name:    "Orc",
		Neutral: "ORC",
	},
	55: &Race{
		ID:     55,
		Name:   "Beggar",
		Male:   "BGM",
		Female: "BGF",
	},
	56: &Race{
		ID:     56,
		Name:   "Pixie",
		Male:   "PIM",
		Female: "PIF",
	},
	57: &Race{
		ID:     57,
		Name:   "Drachnid",
		Male:   "DRM",
		Female: "DRF",
	},
	58: &Race{
		ID:      58,
		Name:    "Solusek Ro",
		Neutral: "SOL",
	},
	59: &Race{
		ID:      59,
		Name:    "Goblin",
		Neutral: "BGG",
	},
	60: &Race{
		ID:      60,
		Name:    "Skeleton",
		Neutral: "SKE",
	},
	61: &Race{
		ID:      61,
		Name:    "Shark",
		Neutral: "SHA",
	},
	62: &Race{
		ID:      62,
		Name:    "Tunare",
		Neutral: "TUN",
	},
	63: &Race{
		ID:      63,
		Name:    "Tiger",
		Neutral: "TIG",
	},
	64: &Race{
		ID:      64,
		Name:    "Treant",
		Neutral: "TRE",
	},
	65: &Race{
		ID:     65,
		Name:   "Vampire",
		Male:   "DVM",
		Female: "DVF",
	},
	66: &Race{
		ID:      66,
		Name:    "Rallos Zek",
		Neutral: "RAL",
	},
	67: &Race{
		ID:     67,
		Name:   "Human",
		Male:   "HHM",
		Female: "HHF",
	},
	68: &Race{
		ID:      68,
		Name:    "Tentacle Terror",
		Male:    "TEM",
		Female:  "TEF",
		Neutral: "TEN",
	},
	69: &Race{
		ID:      69,
		Name:    "Will-O-Wisp",
		Neutral: "WIL",
	},
	70: &Race{
		ID:     70,
		Name:   "Zombie",
		Male:   "ZOM",
		Female: "ZOF",
	},
	71: &Race{
		ID:     71,
		Name:   "Human",
		Male:   "QCM",
		Female: "QCF",
	},
	72: &Race{
		ID:      72,
		Name:    "Ship",
		Male:    "SHIP",
		Female:  "PRE",
		Neutral: "PRE",
	},
	73: &Race{
		ID:      73,
		Name:    "Launch",
		Male:    "LAUNCHM",
		Neutral: "LAUNCH",
	},
	74: &Race{
		ID:      74,
		Name:    "Piranha",
		Neutral: "PIR",
	},
	75: &Race{
		ID:      75,
		Name:    "Elemental",
		Neutral: "ELE",
	},
	76: &Race{
		ID:      76,
		Name:    "Puma",
		Neutral: "PUM",
	},
	77: &Race{
		ID:     77,
		Name:   "Dark Elf",
		Male:   "NGM",
		Female: "NGF",
	},
	78: &Race{
		ID:     78,
		Name:   "Erudite",
		Male:   "EGM",
		Female: "EGF",
	},
	79: &Race{
		ID:      79,
		Name:    "Bixie",
		Neutral: "BIX",
	},
	80: &Race{
		ID:      80,
		Name:    "Reanimated Hand",
		Neutral: "REA",
	},
	81: &Race{
		ID:     81,
		Name:   "Halfling",
		Male:   "RIM",
		Female: "RIF",
	},
	82: &Race{
		ID:      82,
		Name:    "Scarecrow",
		Neutral: "SCA",
	},
	83: &Race{
		ID:      83,
		Name:    "Skunk",
		Neutral: "SKU",
	},
	84: &Race{
		ID:      84,
		Name:    "Snake Elemental",
		Neutral: "SNE",
	},
	85: &Race{
		ID:      85,
		Name:    "Spectre",
		Neutral: "SPE",
	},
	86: &Race{
		ID:      86,
		Name:    "Sphinx",
		Neutral: "SPH",
	},
	87: &Race{
		ID:      87,
		Name:    "Armadillo",
		Neutral: "ARM",
	},
	88: &Race{
		ID:      88,
		Name:    "Clockwork Gnome",
		Male:    "CLM",
		Female:  "CLF",
		Neutral: "CLN",
	},
	89: &Race{
		ID:      89,
		Name:    "Drake",
		Neutral: "DRK",
	},
	90: &Race{
		ID:     90,
		Name:   "Barbarian",
		Male:   "HLM",
		Female: "HLF",
	},
	91: &Race{
		ID:      91,
		Name:    "Alligator",
		Neutral: "ALL",
	},
	92: &Race{
		ID:     92,
		Name:   "Troll",
		Male:   "GRM",
		Female: "GRF",
	},
	93: &Race{
		ID:     93,
		Name:   "Ogre",
		Male:   "OKM",
		Female: "OKF",
	},
	94: &Race{
		ID:      94,
		Name:    "Dwarf",
		Male:    "KAM",
		Female:  "KAF",
		Neutral: "KAN",
	},
	95: &Race{
		ID:      95,
		Name:    "Cazic Thule",
		Neutral: "CAZ",
	},
	96: &Race{
		ID:      96,
		Name:    "Cockatrice",
		Neutral: "COC",
	},
	97: &Race{
		ID:      97,
		Name:    "Daisy Man",
		Neutral: "DIA",
	},
	98: &Race{
		ID:     98,
		Name:   "Vampire",
		Male:   "VSM",
		Female: "VSF",
	},
	99: &Race{
		ID:      99,
		Name:    "Amygdalan",
		Neutral: "DEN",
	},
	100: &Race{
		ID:      100,
		Name:    "Dervish",
		Neutral: "DER",
	},
	101: &Race{
		ID:      101,
		Name:    "Efreeti",
		Neutral: "EFR",
	},
	102: &Race{
		ID:      102,
		Name:    "Tadpole",
		Neutral: "FRT",
	},
	103: &Race{
		ID:      103,
		Name:    "Kedge",
		Neutral: "KED",
	},
	104: &Race{
		ID:      104,
		Name:    "Leech",
		Neutral: "LEE",
	},
	105: &Race{
		ID:      105,
		Name:    "Swordfish",
		Neutral: "SWO",
	},
	106: &Race{
		ID:     106,
		Name:   "Guard",
		Male:   "FEM",
		Female: "FEF",
	},
	107: &Race{
		ID:      107,
		Name:    "Mammoth",
		Neutral: "MAM",
	},
	108: &Race{
		ID:      108,
		Name:    "Eye",
		Neutral: "EYE",
	},
	109: &Race{
		ID:      109,
		Name:    "Wasp",
		Neutral: "WAS",
	},
	110: &Race{
		ID:      110,
		Name:    "Mermaid",
		Neutral: "MER",
	},
	111: &Race{
		ID:      111,
		Name:    "Harpy",
		Neutral: "HAR",
	},
	112: &Race{
		ID:     112,
		Name:   "Guard",
		Male:   "GFM",
		Female: "GFF",
	},
	113: &Race{
		ID:      113,
		Name:    "Drixie",
		Neutral: "DRI",
	},
	114: &Race{
		ID:      114,
		Name:    "Ghost Ship",
		Neutral: "GSP",
	},
	115: &Race{
		ID:      115,
		Name:    "Clam",
		Neutral: "CLA",
	},
	116: &Race{
		ID:      116,
		Name:    "Seahorse",
		Neutral: "SEA",
	},
	117: &Race{
		ID:     117,
		Name:   "Ghost",
		Male:   "GDM",
		Female: "GDF",
	},
	118: &Race{
		ID:     118,
		Name:   "Ghost",
		Male:   "GEM",
		Female: "GEF",
	},
	119: &Race{
		ID:      119,
		Name:    "Saber-toothed Cat",
		Neutral: "STC",
	},
	120: &Race{
		ID:      120,
		Name:    "Wolf",
		Neutral: "WOE",
	},
	121: &Race{
		ID:      121,
		Name:    "Gorgon",
		Neutral: "GRG",
	},
	122: &Race{
		ID:      122,
		Name:    "Dragon",
		Neutral: "DRU",
	},
	123: &Race{
		ID:      123,
		Name:    "Innoruuk",
		Neutral: "INN",
	},
	124: &Race{
		ID:      124,
		Name:    "Unicorn",
		Neutral: "UNI",
	},
	125: &Race{
		ID:      125,
		Name:    "Pegasus",
		Neutral: "PEG",
	},
	126: &Race{
		ID:      126,
		Name:    "Djinn",
		Neutral: "DJI",
	},
	127: &Race{
		ID:     127,
		Name:   "Invisible Man",
		Male:   "IVM",
		Female: "IVF",
	},
	128: &Race{
		ID:     128,
		Name:   "Iksar",
		Male:   "IKM",
		Female: "IKF",
	},
	129: &Race{
		ID:      129,
		Name:    "Scorpion",
		Neutral: "SCR",
	},
	130: &Race{
		ID:     130,
		Name:   "Vah Shir",
		Male:   "KEM",
		Female: "KEF",
	},
	131: &Race{
		ID:      131,
		Name:    "Sarnak",
		Neutral: "SRW",
	},
	132: &Race{
		ID:      132,
		Name:    "Draglock",
		Neutral: "DLK",
	},
	133: &Race{
		ID:      133,
		Name:    "Drolvarg",
		Neutral: "LYC",
	},
	134: &Race{
		ID:      134,
		Name:    "Mosquito",
		Neutral: "MOS",
	},
	135: &Race{
		ID:      135,
		Name:    "Rhinoceros",
		Neutral: "RHI",
	},
	136: &Race{
		ID:      136,
		Name:    "Xalgoz",
		Neutral: "XAL",
	},
	137: &Race{
		ID:      137,
		Name:    "Goblin",
		Neutral: "KGO",
	},
	138: &Race{
		ID:      138,
		Name:    "Yeti",
		Neutral: "YET",
	},
	139: &Race{
		ID:      139,
		Name:    "Iksar",
		Male:    "ICM",
		Female:  "ICF",
		Neutral: "ICN",
	},
	140: &Race{
		ID:      140,
		Name:    "Giant",
		Neutral: "FGI",
	},
	141: &Race{
		ID:      141,
		Name:    "Boat",
		Male:    "BOAT",
		Female:  "BOAT",
		Neutral: "BOAT",
	},
	144: &Race{
		ID:      144,
		Name:    "Burynai",
		Neutral: "BRN",
	},
	145: &Race{
		ID:      145,
		Name:    "Goo",
		Neutral: "GOO",
	},
	146: &Race{
		ID:      146,
		Name:    "Sarnak Spirit",
		Neutral: "SSN",
	},
	147: &Race{
		ID:     147,
		Name:   "Iksar Spirit",
		Male:   "SIM",
		Female: "SIF",
	},
	148: &Race{
		ID:      148,
		Name:    "Fish",
		Neutral: "BAC",
	},
	149: &Race{
		ID:      149,
		Name:    "Scorpion",
		Neutral: "ISC",
	},
	150: &Race{
		ID:      150,
		Name:    "Erollisi",
		Neutral: "ERO",
	},
	151: &Race{
		ID:      151,
		Name:    "Tribunal",
		Neutral: "TRI",
	},
	152: &Race{
		ID:      152,
		Name:    "Bertoxxulous",
		Neutral: "BER",
	},
	153: &Race{
		ID:      153,
		Name:    "Bristlebane",
		Neutral: "BRI",
	},
	154: &Race{
		ID:      154,
		Name:    "Fay Drake",
		Neutral: "FDR",
	},
	155: &Race{
		ID:      155,
		Name:    "Undead Sarnak",
		Neutral: "SSK",
	},
	156: &Race{
		ID:      156,
		Name:    "Ratman",
		Neutral: "VRM",
	},
	157: &Race{
		ID:      157,
		Name:    "Wyvern",
		Neutral: "WYV",
	},
	158: &Race{
		ID:      158,
		Name:    "Wurm",
		Neutral: "WUR",
	},
	159: &Race{
		ID:      159,
		Name:    "Devourer",
		Neutral: "DEV",
	},
	160: &Race{
		ID:      160,
		Name:    "Iksar Golem",
		Neutral: "IKG",
	},
	161: &Race{
		ID:      161,
		Name:    "Undead Iksar",
		Neutral: "IKS",
	},
	162: &Race{
		ID:      162,
		Name:    "Man-Eating Plant",
		Neutral: "MEP",
	},
	163: &Race{
		ID:      163,
		Name:    "Raptor",
		Neutral: "RAP",
	},
	164: &Race{
		ID:      164,
		Name:    "Sarnak Golem",
		Neutral: "SGO",
	},
	165: &Race{
		ID:      165,
		Name:    "Dragon",
		Neutral: "SED",
	},
	166: &Race{
		ID:      166,
		Name:    "Animated Hand",
		Neutral: "IKH",
	},
	167: &Race{
		ID:      167,
		Name:    "Succulent",
		Neutral: "SUC",
	},
	168: &Race{
		ID:      168,
		Name:    "Holgresh",
		Neutral: "FMO",
	},
	169: &Race{
		ID:      169,
		Name:    "Brontotherium",
		Neutral: "BTM",
	},
	170: &Race{
		ID:      170,
		Name:    "Snow Dervish",
		Neutral: "SDE",
	},
	171: &Race{
		ID:      171,
		Name:    "Dire Wolf",
		Neutral: "DIW",
	},
	172: &Race{
		ID:      172,
		Name:    "Manticore",
		Neutral: "MTC",
	},
	173: &Race{
		ID:      173,
		Name:    "Totem",
		Neutral: "TOT",
	},
	174: &Race{
		ID:      174,
		Name:    "Ice Spectre",
		Neutral: "SPC",
	},
	175: &Race{
		ID:      175,
		Name:    "Enchanted Armor",
		Neutral: "ENA",
	},
	176: &Race{
		ID:      176,
		Name:    "Snow Rabbit",
		Neutral: "SBU",
	},
	177: &Race{
		ID:      177,
		Name:    "Walrus",
		Neutral: "WAL",
	},
	178: &Race{
		ID:      178,
		Name:    "Geonid",
		Neutral: "RGM",
	},
	181: &Race{
		ID:      181,
		Name:    "Yakkar",
		Neutral: "YAK",
	},
	182: &Race{
		ID:      182,
		Name:    "Faun",
		Neutral: "FAN",
	},
	183: &Race{
		ID:      183,
		Name:    "Coldain",
		Male:    "COM",
		Female:  "COF",
		Neutral: "COK",
	},
	184: &Race{
		ID:      184,
		Name:    "Dragon",
		Neutral: "DR2",
	},
	185: &Race{
		ID:      185,
		Name:    "Hag",
		Neutral: "HAG",
	},
	186: &Race{
		ID:      186,
		Name:    "Hippogriff",
		Neutral: "HIP",
	},
	187: &Race{
		ID:      187,
		Name:    "Siren",
		Neutral: "SIR",
	},
	188: &Race{
		ID:      188,
		Name:    "Giant",
		Neutral: "FSG",
	},
	189: &Race{
		ID:      189,
		Name:    "Giant",
		Male:    "STM",
		Neutral: "STG",
	},
	190: &Race{
		ID:      190,
		Name:    "Othmir",
		Neutral: "OTM",
	},
	191: &Race{
		ID:      191,
		Name:    "Ulthork",
		Neutral: "WLM",
	},
	192: &Race{
		ID:      192,
		Name:    "Dragon",
		Neutral: "CCD",
	},
	193: &Race{
		ID:      193,
		Name:    "Abhorrent",
		Neutral: "ABH",
	},
	194: &Race{
		ID:      194,
		Name:    "Sea Turtle",
		Neutral: "STU",
	},
	195: &Race{
		ID:      195,
		Name:    "Dragon",
		Neutral: "BWD",
	},
	196: &Race{
		ID:      196,
		Name:    "Dragon",
		Neutral: "GDR",
	},
	197: &Race{
		ID:      197,
		Name:    "Ronnie Test",
		Neutral: "RON",
	},
	198: &Race{
		ID:      198,
		Name:    "Dragon",
		Neutral: "PRI",
	},
	199: &Race{
		ID:      199,
		Name:    "Shik'Nar",
		Neutral: "SKN",
	},
	200: &Race{
		ID:      200,
		Name:    "Rockhopper",
		Neutral: "RHP",
	},
	201: &Race{
		ID:      201,
		Name:    "Underbulk",
		Neutral: "UNB",
	},
	202: &Race{
		ID:      202,
		Name:    "Grimling",
		Male:    "GMM",
		Female:  "GMF",
		Neutral: "GMN",
	},
	203: &Race{
		ID:      203,
		Name:    "Worm",
		Neutral: "VAC",
	},
	204: &Race{
		ID:      204,
		Name:    "Evan Test",
		Neutral: "ECS",
	},
	205: &Race{
		ID:      205,
		Name:    "Shadel",
		Neutral: "KHA",
	},
	206: &Race{
		ID:      206,
		Name:    "Owlbear",
		Neutral: "OWB",
	},
	207: &Race{
		ID:      207,
		Name:    "Rhino Beetle",
		Neutral: "RNB",
	},
	208: &Race{
		ID:     208,
		Name:   "Vampire",
		Male:   "VPM",
		Female: "VPF",
	},
	209: &Race{
		ID:      209,
		Name:    "Earth Elemental",
		Neutral: "EEL",
	},
	210: &Race{
		ID:      210,
		Name:    "Air Elemental",
		Neutral: "AEL",
	},
	211: &Race{
		ID:      211,
		Name:    "Water Elemental",
		Neutral: "WEL",
	},
	212: &Race{
		ID:      212,
		Name:    "Fire Elemental",
		Neutral: "FEL",
	},
	213: &Race{
		ID:      213,
		Name:    "Wetfang Minnow",
		Neutral: "WET",
	},
	214: &Race{
		ID:      214,
		Name:    "Thought Horror",
		Neutral: "THO",
	},
	215: &Race{
		ID:      215,
		Name:    "Tegi",
		Neutral: "TEG",
	},
	216: &Race{
		ID:      216,
		Name:    "Horse",
		Male:    "HSM",
		Female:  "HSF",
		Neutral: "HSN",
	},
	217: &Race{
		ID:      217,
		Name:    "Shissar",
		Male:    "SHM",
		Female:  "SHF",
		Neutral: "SHN",
	},
	218: &Race{
		ID:      218,
		Name:    "Fungal Fiend",
		Neutral: "FUG",
	},
	219: &Race{
		ID:      219,
		Name:    "Vampire",
		Neutral: "VOL",
	},
	220: &Race{
		ID:      220,
		Name:    "Stonegrabber",
		Neutral: "SGR",
	},
	221: &Race{
		ID:      221,
		Name:    "Scarlet Cheetah",
		Neutral: "SCH",
	},
	222: &Race{
		ID:      222,
		Name:    "Zelniak",
		Neutral: "ZEL",
	},
	223: &Race{
		ID:      223,
		Name:    "Lightcrawler",
		Neutral: "LCR",
	},
	224: &Race{
		ID:     224,
		Name:   "Shade",
		Male:   "SDM",
		Female: "SDF",
	},
	225: &Race{
		ID:      225,
		Name:    "Sunflower",
		Neutral: "SNN",
	},
	226: &Race{
		ID:      226,
		Name:    "Sun Revenant",
		Neutral: "SRV",
	},
	227: &Race{
		ID:      227,
		Name:    "Shrieker",
		Neutral: "SHR",
	},
	228: &Race{
		ID:      228,
		Name:    "Galorian",
		Neutral: "GAL",
	},
	229: &Race{
		ID:      229,
		Name:    "Netherbian",
		Neutral: "NET",
	},
	230: &Race{
		ID:      230,
		Name:    "Akheva",
		Male:    "AKM",
		Female:  "AKF",
		Neutral: "AKN",
	},
	231: &Race{
		ID:      231,
		Name:    "Grieg Veneficus",
		Neutral: "SPR",
	},
	232: &Race{
		ID:      232,
		Name:    "Sonic Wolf",
		Neutral: "SOW",
	},
	233: &Race{
		ID:      233,
		Name:    "Ground Shaker",
		Male:    "GSM",
		Female:  "GSF",
		Neutral: "GSN",
	},
	234: &Race{
		ID:      234,
		Name:    "Vah Shir Skeleton",
		Neutral: "KES",
	},
	235: &Race{
		ID:      235,
		Name:    "Wretch",
		Neutral: "MUH",
	},
	236: &Race{
		ID:      236,
		Name:    "Seru",
		Neutral: "SER",
	},
	237: &Race{
		ID:      237,
		Name:    "Recuso",
		Male:    "REM",
		Female:  "REF",
		Neutral: "REN",
	},
	238: &Race{
		ID:      238,
		Name:    "Vah Shir",
		Neutral: "VSK",
	},
	239: &Race{
		ID:      239,
		Name:    "Guard",
		Neutral: "VSG",
	},
	240: &Race{
		ID:      240,
		Name:    "Teleport Man",
		Male:    "TPM",
		Female:  "TPF",
		Neutral: "TPN",
	},
	241: &Race{
		ID:      241,
		Name:    "Werewolf",
		Neutral: "LUJ",
	},
	242: &Race{
		ID:      242,
		Name:    "Nymph",
		Neutral: "NYD",
	},
	243: &Race{
		ID:      243,
		Name:    "Dryad",
		Neutral: "NYM",
	},
	244: &Race{
		ID:      244,
		Name:    "Treant",
		Neutral: "TRN",
	},
	245: &Race{
		ID:      245,
		Name:    "Fly",
		Neutral: "WRF",
	},
	246: &Race{
		ID:      246,
		Name:    "Tarew Marr",
		Neutral: "TMR",
	},
	247: &Race{
		ID:      247,
		Name:    "Solusek Ro",
		Neutral: "SRO",
	},
	248: &Race{
		ID:      248,
		Name:    "Clockwork Golem",
		Neutral: "CLG",
	},
	249: &Race{
		ID:      249,
		Name:    "Clockwork Brain",
		Neutral: "CLB",
	},
	250: &Race{
		ID:      250,
		Name:    "Banshee",
		Neutral: "SKB",
	},
	251: &Race{
		ID:      251,
		Name:    "Guard of Justice",
		Neutral: "GOJ",
	},
	252: &Race{
		ID:      252,
		Name:    "Mini POM",
		Male:    "MINIPOM200",
		Female:  "MINIPOM200",
		Neutral: "MINIPOM200",
	},
	253: &Race{
		ID:      253,
		Name:    "Diseased Fiend",
		Neutral: "DSB",
	},
	254: &Race{
		ID:      254,
		Name:    "Solusek Ro Guard",
		Neutral: "SRG",
	},
	255: &Race{
		ID:      255,
		Name:    "Bertoxxulous",
		Neutral: "BTX",
	},
	256: &Race{
		ID:      256,
		Name:    "The Tribunal",
		Neutral: "TBU",
	},
	257: &Race{
		ID:      257,
		Name:    "Terris Thule",
		Neutral: "TRT",
	},
	258: &Race{
		ID:      258,
		Name:    "Vegerog",
		Neutral: "VEG",
	},
	259: &Race{
		ID:      259,
		Name:    "Crocodile",
		Neutral: "CRO",
	},
	260: &Race{
		ID:      260,
		Name:    "Bat",
		Neutral: "NBT",
	},
	261: &Race{
		ID:      261,
		Name:    "Hraquis",
		Neutral: "SLG",
	},
	262: &Race{
		ID:      262,
		Name:    "Tranquilion",
		Neutral: "TRQ",
	},
	263: &Race{
		ID:      263,
		Name:    "Tin Soldier",
		Neutral: "TIN",
	},
	264: &Race{
		ID:      264,
		Name:    "Nightmare Wraith",
		Neutral: "NMW",
	},
	265: &Race{
		ID:      265,
		Name:    "Malarian",
		Neutral: "MAL",
	},
	266: &Race{
		ID:      266,
		Name:    "Knight of Pestilence",
		Neutral: "KOP",
	},
	267: &Race{
		ID:      267,
		Name:    "Lepertoloth",
		Neutral: "LEP",
	},
	268: &Race{
		ID:      268,
		Name:    "Bubonian",
		Neutral: "BUB",
	},
	269: &Race{
		ID:      269,
		Name:    "Bubonian Underling",
		Neutral: "BUU",
	},
	270: &Race{
		ID:      270,
		Name:    "Pusling",
		Neutral: "PUS",
	},
	271: &Race{
		ID:      271,
		Name:    "Water Mephit",
		Neutral: "WMP",
	},
	272: &Race{
		ID:      272,
		Name:    "Stormrider",
		Neutral: "STR",
	},
	273: &Race{
		ID:      273,
		Name:    "Junk Beast",
		Neutral: "JUB",
	},
	274: &Race{
		ID:      274,
		Name:    "Broken Clockwork",
		Neutral: "BRC",
	},
	275: &Race{
		ID:      275,
		Name:    "Giant Clockwork",
		Neutral: "GLC",
	},
	276: &Race{
		ID:      276,
		Name:    "Clockwork Beetle",
		Neutral: "CWB",
	},
	277: &Race{
		ID:      277,
		Name:    "Nightmare Goblin",
		Neutral: "NMG",
	},
	278: &Race{
		ID:      278,
		Name:    "Karana",
		Neutral: "KAR",
	},
	279: &Race{
		ID:      279,
		Name:    "Blood Raven",
		Neutral: "BRV",
	},
	280: &Race{
		ID:      280,
		Name:    "Nightmare Gargoyle",
		Neutral: "GGL",
	},
	281: &Race{
		ID:      281,
		Name:    "Mouth of Insanity",
		Neutral: "MOI",
	},
	282: &Race{
		ID:      282,
		Name:    "Skeletal Horse",
		Neutral: "HSS",
	},
	283: &Race{
		ID:      283,
		Name:    "Saryrn",
		Neutral: "SAR",
	},
	284: &Race{
		ID:      284,
		Name:    "Fennin Ro",
		Neutral: "FEN",
	},
	285: &Race{
		ID:      285,
		Name:    "Tormentor",
		Neutral: "TRW",
	},
	286: &Race{
		ID:      286,
		Name:    "Soul Devourer",
		Neutral: "NPT",
	},
	287: &Race{
		ID:      287,
		Name:    "Nightmare",
		Neutral: "NMH",
	},
	288: &Race{
		ID:      288,
		Name:    "Rallos Zek",
		Neutral: "RAZ",
	},
	289: &Race{
		ID:      289,
		Name:    "Vallon Zek",
		Neutral: "VAZ",
	},
	290: &Race{
		ID:      290,
		Name:    "Tallon Zek",
		Neutral: "TAZ",
	},
	291: &Race{
		ID:      291,
		Name:    "Air Mephit",
		Neutral: "AMP",
	},
	292: &Race{
		ID:      292,
		Name:    "Earth Mephit",
		Neutral: "EMP",
	},
	293: &Race{
		ID:      293,
		Name:    "Fire Mephit",
		Neutral: "FMP",
	},
	294: &Race{
		ID:      294,
		Name:    "Nightmare Mephit",
		Neutral: "NMP",
	},
	295: &Race{
		ID:      295,
		Name:    "Zebuxoruk",
		Neutral: "ZEB",
	},
	296: &Race{
		ID:      296,
		Name:    "Mithaniel Marr",
		Neutral: "MAR",
	},
	297: &Race{
		ID:      297,
		Name:    "Undead Knight",
		Neutral: "UDK",
	},
	298: &Race{
		ID:      298,
		Name:    "The Rathe",
		Neutral: "RTH",
	},
	299: &Race{
		ID:      299,
		Name:    "Xegony",
		Neutral: "XEG",
	},
	300: &Race{
		ID:      300,
		Name:    "Fiend",
		Neutral: "GTD",
	},
	301: &Race{
		ID:      301,
		Name:    "Test Object",
		Neutral: "ONT",
	},
	302: &Race{
		ID:      302,
		Name:    "Crab",
		Neutral: "CRB",
	},
	303: &Race{
		ID:      303,
		Name:    "Phoenix",
		Neutral: "PHX",
	},
	304: &Race{
		ID:      304,
		Name:    "Dragon",
		Neutral: "TMT",
	},
	305: &Race{
		ID:      305,
		Name:    "Bear",
		Neutral: "PBR",
	},
	306: &Race{
		ID:      306,
		Name:    "Giant",
		Neutral: "STA",
	},
	307: &Race{
		ID:      307,
		Name:    "Giant",
		Neutral: "SSA",
	},
	308: &Race{
		ID:      308,
		Name:    "Giant",
		Neutral: "SKR",
	},
	309: &Race{
		ID:      309,
		Name:    "Giant",
		Neutral: "SVO",
	},
	310: &Race{
		ID:      310,
		Name:    "Giant",
		Neutral: "SMA",
	},
	311: &Race{
		ID:      311,
		Name:    "Giant",
		Neutral: "STF",
	},
	312: &Race{
		ID:      312,
		Name:    "Giant",
		Neutral: "SCE",
	},
	313: &Race{
		ID:      313,
		Name:    "War Wraith",
		Neutral: "WRW",
	},
	314: &Race{
		ID:      314,
		Name:    "Wrulon",
		Neutral: "WRU",
	},
	315: &Race{
		ID:      315,
		Name:    "Kraken",
		Neutral: "KRK",
	},
	316: &Race{
		ID:      316,
		Name:    "Poison Frog",
		Neutral: "PAF",
	},
	317: &Race{
		ID:      317,
		Name:    "Nilborien",
		Neutral: "QZT",
	},
	318: &Race{
		ID:      318,
		Name:    "Valorian",
		Neutral: "VAL",
	},
	319: &Race{
		ID:      319,
		Name:    "War Boar",
		Neutral: "WRB",
	},
	320: &Race{
		ID:      320,
		Name:    "Efreeti",
		Neutral: "EFE",
	},
	321: &Race{
		ID:      321,
		Name:    "War Boar",
		Neutral: "WBU",
	},
	322: &Race{
		ID:      322,
		Name:    "Valorian",
		Neutral: "BKN",
	},
	323: &Race{
		ID:      323,
		Name:    "Animated Armor",
		Neutral: "AAM",
	},
	324: &Race{
		ID:      324,
		Name:    "Undead Footman",
		Neutral: "UDF",
	},
	325: &Race{
		ID:      325,
		Name:    "Rallos Zek Minion",
		Neutral: "RZM",
	},
	326: &Race{
		ID:      326,
		Name:    "Arachnid",
		Neutral: "SPD",
	},
	327: &Race{
		ID:      327,
		Name:    "Crystal Spider",
		Neutral: "SPL",
	},
	328: &Race{
		ID:      328,
		Name:    "Zebuxoruk's Cage",
		Neutral: "ZBC",
	},
	329: &Race{
		ID:      329,
		Name:    "BoT Portal",
		Neutral: "BTP",
	},
	330: &Race{
		ID:     330,
		Name:   "Froglok",
		Male:   "FRM",
		Female: "FRF",
	},
	331: &Race{
		ID:     331,
		Name:   "Troll",
		Male:   "TBM",
		Female: "TBF",
	},
	332: &Race{
		ID:     332,
		Name:   "Troll",
		Male:   "FBM",
		Female: "FBF",
	},
	333: &Race{
		ID:     333,
		Name:   "Troll",
		Male:   "TSM",
		Female: "TSF",
	},
	334: &Race{
		ID:      334,
		Name:    "Ghost",
		Neutral: "SPB",
	},
	335: &Race{
		ID:      335,
		Name:    "Pirate",
		Neutral: "TPB",
	},
	336: &Race{
		ID:      336,
		Name:    "Pirate",
		Neutral: "TVP",
	},
	337: &Race{
		ID:      337,
		Name:    "Pirate",
		Neutral: "TPO",
	},
	338: &Race{
		ID:     338,
		Name:   "Pirate",
		Male:   "GPM",
		Female: "GPF",
	},
	339: &Race{
		ID:     339,
		Name:   "Pirate",
		Male:   "DPM",
		Female: "DPF",
	},
	340: &Race{
		ID:     340,
		Name:   "Pirate",
		Male:   "OPM",
		Female: "OPF",
	},
	341: &Race{
		ID:     341,
		Name:   "Pirate",
		Male:   "HPM",
		Female: "HPF",
	},
	342: &Race{
		ID:     342,
		Name:   "Pirate",
		Male:   "EPM",
		Female: "EPF",
	},
	343: &Race{
		ID:      343,
		Name:    "Frog",
		Neutral: "RPF",
	},
	344: &Race{
		ID:     344,
		Name:   "Troll Zombie",
		Male:   "TZM",
		Female: "TZF",
	},
	345: &Race{
		ID:      345,
		Name:    "Luggald",
		Neutral: "LUG",
	},
	346: &Race{
		ID:      346,
		Name:    "Luggald",
		Neutral: "LGA",
	},
	347: &Race{
		ID:      347,
		Name:    "Luggalds",
		Neutral: "LGR",
	},
	348: &Race{
		ID:      348,
		Name:    "Drogmore",
		Neutral: "FMT",
	},
	349: &Race{
		ID:      349,
		Name:    "Froglok Skeleton",
		Neutral: "FSK",
	},
	350: &Race{
		ID:      350,
		Name:    "Undead Froglok",
		Neutral: "FUD",
	},
	351: &Race{
		ID:     351,
		Name:   "Knight of Hate",
		Male:   "IWM",
		Female: "IWF",
	},
	352: &Race{
		ID:     352,
		Name:   "Arcanist of Hate",
		Male:   "IZM",
		Female: "IZF",
	},
	353: &Race{
		ID:      353,
		Name:    "Veksar",
		Neutral: "VEK",
	},
	354: &Race{
		ID:      354,
		Name:    "Veksar",
		Neutral: "GVK",
	},
	355: &Race{
		ID:      355,
		Name:    "Veksar",
		Neutral: "BVK",
	},
	356: &Race{
		ID:      356,
		Name:    "Chokidai",
		Neutral: "WOF",
	},
	357: &Race{
		ID:      357,
		Name:    "Undead Chokidai",
		Neutral: "WUF",
	},
	358: &Race{
		ID:      358,
		Name:    "Undead Veksar",
		Neutral: "UVK",
	},
	359: &Race{
		ID:     359,
		Name:   "Vampire",
		Male:   "LMM",
		Female: "LMF",
	},
	360: &Race{
		ID:     360,
		Name:   "Vampire",
		Male:   "MMM",
		Female: "MMF",
	},
	361: &Race{
		ID:      361,
		Name:    "Rujarkian Orc",
		Neutral: "ROM",
	},
	362: &Race{
		ID:      362,
		Name:    "Bone Golem",
		Neutral: "BGB",
	},
	363: &Race{
		ID:      363,
		Name:    "Synarcana",
		Neutral: "SYN",
	},
	364: &Race{
		ID:     364,
		Name:   "Sand Elf",
		Male:   "SEM",
		Female: "SEF",
	},
	365: &Race{
		ID:      365,
		Name:    "Vampire",
		Neutral: "MMV",
	},
	366: &Race{
		ID:      366,
		Name:    "Rujarkian Orc",
		Neutral: "ROE",
	},
	367: &Race{
		ID:      367,
		Name:    "Skeleton",
		Neutral: "SKT",
	},
	368: &Race{
		ID:      368,
		Name:    "Mummy",
		Neutral: "MMY",
	},
	369: &Race{
		ID:      369,
		Name:    "Goblin",
		Neutral: "GBL",
	},
	370: &Race{
		ID:      370,
		Name:    "Insect",
		Neutral: "NIN",
	},
	371: &Race{
		ID:      371,
		Name:    "Froglok Ghost",
		Neutral: "FGH",
	},
	372: &Race{
		ID:      372,
		Name:    "Dervish",
		Neutral: "DRV",
	},
	373: &Race{
		ID:      373,
		Name:    "Shade",
		Neutral: "SDC",
	},
	374: &Race{
		ID:      374,
		Name:    "Golem",
		Neutral: "GLM",
	},
	375: &Race{
		ID:      375,
		Name:    "Evil Eye",
		Neutral: "EEY",
	},
	376: &Race{
		ID:      376,
		Name:    "Box",
		Neutral: "BOX",
	},
	377: &Race{
		ID:      377,
		Name:    "Barrel",
		Neutral: "BRL",
	},
	378: &Race{
		ID:      378,
		Name:    "Chest",
		Neutral: "CST",
	},
	379: &Race{
		ID:      379,
		Name:    "Vase",
		Neutral: "VAS",
	},
	380: &Race{
		ID:      380,
		Name:    "Table",
		Neutral: "TBL",
	},
	381: &Race{
		ID:      381,
		Name:    "Weapon Rack",
		Neutral: "RAK",
	},
	382: &Race{
		ID:      382,
		Name:    "Coffin",
		Neutral: "CPT",
	},
	383: &Race{
		ID:      383,
		Name:    "Bones",
		Neutral: "BON",
	},
	384: &Race{
		ID:      384,
		Name:    "Jokester",
		Neutral: "JKR",
	},
	385: &Race{
		ID:     385,
		Name:   "Nihil",
		Male:   "TNM",
		Female: "TNF",
	},
	386: &Race{
		ID:     386,
		Name:   "Trusik",
		Male:   "TEM",
		Female: "TEF",
	},
	387: &Race{
		ID:      387,
		Name:    "Stone Worker",
		Neutral: "TGL",
	},
	388: &Race{
		ID:      388,
		Name:    "Hynid",
		Neutral: "TWF",
	},
	389: &Race{
		ID:      389,
		Name:    "Turepta",
		Neutral: "TAC",
	},
	390: &Race{
		ID:      390,
		Name:    "Cragbeast",
		Neutral: "TMB",
	},
	391: &Race{
		ID:      391,
		Name:    "Stonemite",
		Neutral: "TTB",
	},
	392: &Race{
		ID:      392,
		Name:    "Ukun",
		Neutral: "IWH",
	},
	393: &Race{
		ID:      393,
		Name:    "Ixt",
		Neutral: "IEC",
	},
	394: &Race{
		ID:      394,
		Name:    "Ikaav",
		Neutral: "ILA",
	},
	395: &Race{
		ID:      395,
		Name:    "Aneuk",
		Neutral: "ICY",
	},
	396: &Race{
		ID:      396,
		Name:    "Kyv",
		Neutral: "IHU",
	},
	397: &Race{
		ID:      397,
		Name:    "Noc",
		Neutral: "ISB",
	},
	398: &Race{
		ID:      398,
		Name:    "Ra`tuk",
		Neutral: "IBR",
	},
	399: &Race{
		ID:      399,
		Name:    "Taneth",
		Neutral: "IFC",
	},
	400: &Race{
		ID:      400,
		Name:    "Huvul",
		Neutral: "ILB",
	},
	401: &Race{
		ID:      401,
		Name:    "Mutna",
		Neutral: "IWB",
	},
	402: &Race{
		ID:      402,
		Name:    "Mastruq",
		Neutral: "ISE",
	},
	403: &Race{
		ID:      403,
		Name:    "Taelosian",
		Neutral: "TLN",
	},
	404: &Race{
		ID:      404,
		Name:    "Discord Ship",
		Neutral: "SHP",
	},
	405: &Race{
		ID:      405,
		Name:    "Stone Worker",
		Neutral: "TGO",
	},
	406: &Race{
		ID:      406,
		Name:    "Mata Muram",
		Neutral: "CLV",
	},
	407: &Race{
		ID:      407,
		Name:    "Lightning Warrior",
		Neutral: "MUR",
	},
	408: &Race{
		ID:      408,
		Name:    "Succubus",
		Neutral: "SCU",
	},
	409: &Race{
		ID:      409,
		Name:    "Bazu",
		Neutral: "DSG",
	},
	410: &Race{
		ID:      410,
		Name:    "Feran",
		Neutral: "FRA",
	},
	411: &Race{
		ID:      411,
		Name:    "Pyrilen",
		Neutral: "SCU",
	},
	412: &Race{
		ID:      412,
		Name:    "Chimera",
		Neutral: "CHM",
	},
	413: &Race{
		ID:      413,
		Name:    "Dragorn",
		Neutral: "DDM",
	},
	414: &Race{
		ID:      414,
		Name:    "Murkglider",
		Neutral: "DMA",
	},
	415: &Race{
		ID:      415,
		Name:    "Rat",
		Neutral: "RTN",
	},
	416: &Race{
		ID:      416,
		Name:    "Bat",
		Neutral: "BTN",
	},
	417: &Race{
		ID:      417,
		Name:    "Gelidran",
		Neutral: "FRD",
	},
	418: &Race{
		ID:      418,
		Name:    "Discordling",
		Neutral: "DSF",
	},
	419: &Race{
		ID:      419,
		Name:    "Girplan",
		Neutral: "DDV",
	},
	420: &Race{
		ID:      420,
		Name:    "Minotaur",
		Neutral: "MNT",
	},
	421: &Race{
		ID:      421,
		Name:    "Dragorn Box",
		Neutral: "DBX",
	},
	422: &Race{
		ID:      422,
		Name:    "Runed Orb",
		Neutral: "ROB",
	},
	423: &Race{
		ID:      423,
		Name:    "Dragon Bones",
		Neutral: "DBP",
	},
	424: &Race{
		ID:      424,
		Name:    "Muramite Armor Pile",
		Neutral: "MAP",
	},
	425: &Race{
		ID:      425,
		Name:    "Crystal Shard",
		Neutral: "CRS",
	},
	426: &Race{
		ID:      426,
		Name:    "Portal",
		Neutral: "PRT",
	},
	427: &Race{
		ID:      427,
		Name:    "Coin Purse",
		Neutral: "CNP",
	},
	428: &Race{
		ID:      428,
		Name:    "Rock Pile",
		Neutral: "RKP",
	},
	429: &Race{
		ID:      429,
		Name:    "Murkglider Egg Sac",
		Neutral: "MES",
	},
	430: &Race{
		ID:      430,
		Name:    "Drake",
		Neutral: "CDR",
	},
	431: &Race{
		ID:      431,
		Name:    "Dervish",
		Neutral: "DVS",
	},
	432: &Race{
		ID:      432,
		Name:    "Drake",
		Neutral: "DKE",
	},
	433: &Race{
		ID:      433,
		Name:    "Goblin",
		Neutral: "GBN",
	},
	434: &Race{
		ID:      434,
		Name:    "Kirin",
		Neutral: "KRN",
	},
	435: &Race{
		ID:      435,
		Name:    "Dragon",
		Neutral: "LDR",
	},
	436: &Race{
		ID:      436,
		Name:    "Basilisk",
		Neutral: "BAS",
	},
	437: &Race{
		ID:      437,
		Name:    "Dragon",
		Neutral: "MDR",
	},
	438: &Race{
		ID:      438,
		Name:    "Dragon",
		Neutral: "SDR",
	},
	439: &Race{
		ID:      439,
		Name:    "Puma",
		Neutral: "PMA",
	},
	440: &Race{
		ID:      440,
		Name:    "Spider",
		Neutral: "TAR",
	},
	441: &Race{
		ID:      441,
		Name:    "Spider Queen",
		Neutral: "SPQ",
	},
	442: &Race{
		ID:      442,
		Name:    "Animated Statue",
		Neutral: "ANS",
	},
	445: &Race{
		ID:      445,
		Name:    "Dragon Egg",
		Neutral: "DRE",
	},
	446: &Race{
		ID:      446,
		Name:    "Dragon Statue",
		Neutral: "DRS",
	},
	447: &Race{
		ID:      447,
		Name:    "Lava Rock",
		Neutral: "LVR",
	},
	448: &Race{
		ID:      448,
		Name:    "Animated Statue",
		Neutral: "ASM",
	},
	449: &Race{
		ID:      449,
		Name:    "Spider Egg Sack",
		Neutral: "SEG",
	},
	450: &Race{
		ID:      450,
		Name:    "Lava Spider",
		Neutral: "LSP",
	},
	451: &Race{
		ID:      451,
		Name:    "Lava Spider Queen",
		Neutral: "LSQ",
	},
	452: &Race{
		ID:      452,
		Name:    "Dragon",
		Neutral: "SHD",
	},
	453: &Race{
		ID:      453,
		Name:    "Giant",
		Neutral: "FGT",
	},
	454: &Race{
		ID:      454,
		Name:    "Werewolf",
		Neutral: "WWF",
	},
	455: &Race{
		ID:      455,
		Name:    "Kobold",
		Neutral: "KBD",
	},
	456: &Race{
		ID:      456,
		Name:    "Sporali",
		Neutral: "FNG",
	},
	457: &Race{
		ID:      457,
		Name:    "Gnomework",
		Neutral: "CWG",
	},
	458: &Race{
		ID:      458,
		Name:    "Orc",
		Neutral: "ORK",
	},
	459: &Race{
		ID:      459,
		Name:    "Corathus",
		Neutral: "CRH",
	},
	460: &Race{
		ID:      460,
		Name:    "Coral",
		Neutral: "CRL",
	},
	461: &Race{
		ID:     461,
		Name:   "Drachnid",
		Male:   "DCM",
		Female: "DCF",
	},
	462: &Race{
		ID:      462,
		Name:    "Drachnid Cocoon",
		Neutral: "DRC",
	},
	463: &Race{
		ID:      463,
		Name:    "Fungus Patch",
		Neutral: "FGP",
	},
	464: &Race{
		ID:      464,
		Name:    "Gargoyle",
		Neutral: "GGY",
	},
	465: &Race{
		ID:      465,
		Name:    "Witheran",
		Neutral: "KOR",
	},
	466: &Race{
		ID:      466,
		Name:    "Dark Lord",
		Neutral: "MYG",
	},
	467: &Race{
		ID:      467,
		Name:    "Shiliskin",
		Neutral: "SHL",
	},
	468: &Race{
		ID:      468,
		Name:    "Snake",
		Neutral: "SNK",
	},
	469: &Race{
		ID:      469,
		Name:    "Evil Eye",
		Neutral: "EVE",
	},
	470: &Race{
		ID:      470,
		Name:    "Minotaur",
		Neutral: "MNR",
	},
	471: &Race{
		ID:     471,
		Name:   "Zombie",
		Male:   "ZMM",
		Female: "ZMF",
	},
	472: &Race{
		ID:      472,
		Name:    "Clockwork Boar",
		Neutral: "CWR",
	},
	473: &Race{
		ID:      473,
		Name:    "Fairy",
		Neutral: "FRY",
	},
	474: &Race{
		ID:      474,
		Name:    "Witheran",
		Neutral: "KRB",
	},
	475: &Race{
		ID:      475,
		Name:    "Air Elemental",
		Neutral: "AIE",
	},
	476: &Race{
		ID:      476,
		Name:    "Earth Elemental",
		Neutral: "EAE",
	},
	477: &Race{
		ID:      477,
		Name:    "Fire Elemental",
		Neutral: "FIE",
	},
	478: &Race{
		ID:      478,
		Name:    "Water Elemental",
		Neutral: "WAE",
	},
	479: &Race{
		ID:      479,
		Name:    "Alligator",
		Neutral: "ALR",
	},
	480: &Race{
		ID:      480,
		Name:    "Bear",
		Neutral: "BAR",
	},
	481: &Race{
		ID:      481,
		Name:    "Scaled Wolf",
		Neutral: "SCW",
	},
	482: &Race{
		ID:      482,
		Name:    "Wolf",
		Neutral: "WLF",
	},
	483: &Race{
		ID:      483,
		Name:    "Spirit Wolf",
		Neutral: "SPW",
	},
	484: &Race{
		ID:      484,
		Name:    "Skeleton",
		Neutral: "SKL",
	},
	485: &Race{
		ID:      485,
		Name:    "Spectre",
		Neutral: "SPT",
	},
	486: &Race{
		ID:      486,
		Name:    "Bolvirk",
		Neutral: "BLV",
	},
	487: &Race{
		ID:     487,
		Name:   "Banshee",
		Female: "BSE",
	},
	488: &Race{
		ID:     488,
		Name:   "Banshee",
		Female: "BSG",
	},
	489: &Race{
		ID:     489,
		Name:   "Elddar",
		Male:   "EEM",
		Female: "EEF",
	},
	490: &Race{
		ID:      490,
		Name:    "Forest Giant",
		Neutral: "GFO",
	},
	491: &Race{
		ID:      491,
		Name:    "Bone Golem",
		Neutral: "GLB",
	},
	492: &Race{
		ID:      492,
		Name:    "Horse",
		Neutral: "HRS",
	},
	493: &Race{
		ID:      493,
		Name:    "Pegasus",
		Neutral: "PGS",
	},
	494: &Race{
		ID:      494,
		Name:    "Shambling Mound",
		Neutral: "SMD",
	},
	495: &Race{
		ID:      495,
		Name:    "Scrykin",
		Neutral: "SRN",
	},
	496: &Race{
		ID:      496,
		Name:    "Treant",
		Neutral: "TRA",
	},
	497: &Race{
		ID:     497,
		Name:   "Vampire",
		Male:   "VAM",
		Female: "VAF",
	},
	498: &Race{
		ID:     498,
		Name:   "Ayonae Ro",
		Female: "ARO",
	},
	499: &Race{
		ID:     499,
		Name:   "Sullon Zek",
		Female: "SZK",
	},
	500: &Race{
		ID:      500,
		Name:    "Banner",
		Neutral: "BNR",
	},
	501: &Race{
		ID:      501,
		Name:    "Flag",
		Neutral: "FLG",
	},
	502: &Race{
		ID:      502,
		Name:    "Rowboat",
		Neutral: "ROW",
	},
	503: &Race{
		ID:      503,
		Name:    "Bear Trap",
		Neutral: "T00",
	},
	504: &Race{
		ID:      504,
		Name:    "Clockwork Bomb",
		Neutral: "T01",
	},
	505: &Race{
		ID:      505,
		Name:    "Dynamite Keg",
		Neutral: "T02",
	},
	506: &Race{
		ID:      506,
		Name:    "Pressure Plate",
		Neutral: "T03",
	},
	507: &Race{
		ID:      507,
		Name:    "Puffer Spore",
		Neutral: "T04",
	},
	508: &Race{
		ID:      508,
		Name:    "Stone Ring",
		Neutral: "T05",
	},
	509: &Race{
		ID:      509,
		Name:    "Root Tentacle",
		Neutral: "T06",
	},
	510: &Race{
		ID:      510,
		Name:    "Runic Symbol",
		Neutral: "T07",
	},
	511: &Race{
		ID:      511,
		Name:    "Saltpetter Bomb",
		Neutral: "T08",
	},
	512: &Race{
		ID:      512,
		Name:    "Floating Skull",
		Neutral: "T09",
	},
	513: &Race{
		ID:      513,
		Name:    "Spike Trap",
		Neutral: "T10",
	},
	514: &Race{
		ID:      514,
		Name:    "Totem",
		Neutral: "T11",
	},
	515: &Race{
		ID:      515,
		Name:    "Web",
		Neutral: "T12",
	},
	516: &Race{
		ID:      516,
		Name:    "Wicker Basket",
		Neutral: "T13",
	},
	517: &Race{
		ID:      517,
		Name:    "Nightmare/Unicorn",
		Neutral: "UNM",
	},
	518: &Race{
		ID:      518,
		Name:    "Horse",
		Neutral: "HRS",
	},
	519: &Race{
		ID:      519,
		Name:    "Nightmare/Unicorn",
		Neutral: "UNM",
	},
	520: &Race{
		ID:      520,
		Name:    "Bixie",
		Neutral: "BXI",
	},
	521: &Race{
		ID:      521,
		Name:    "Centaur",
		Neutral: "CNT",
	},
	522: &Race{
		ID:     522,
		Name:   "Drakkin",
		Male:   "DKM",
		Female: "DKF",
	},
	523: &Race{
		ID:      523,
		Name:    "Giant",
		Neutral: "GFR",
	},
	524: &Race{
		ID:      524,
		Name:    "Gnoll",
		Neutral: "GNL",
	},
	525: &Race{
		ID:      525,
		Name:    "Griffin",
		Neutral: "GRN",
	},
	526: &Race{
		ID:      526,
		Name:    "Giant Shade",
		Neutral: "GFS",
	},
	527: &Race{
		ID:      527,
		Name:    "Harpy",
		Neutral: "HRP",
	},
	528: &Race{
		ID:      528,
		Name:    "Mammoth",
		Neutral: "MTH",
	},
	529: &Race{
		ID:      529,
		Name:    "Satyr",
		Neutral: "SAT",
	},
	530: &Race{
		ID:      530,
		Name:    "Dragon",
		Neutral: "DRG",
	},
	531: &Race{
		ID:      531,
		Name:    "Dragon",
		Neutral: "DRN",
	},
	532: &Race{
		ID:      532,
		Name:    "Dyn'Leth",
		Neutral: "DYN",
	},
	533: &Race{
		ID:      533,
		Name:    "Boat",
		Neutral: "SHI",
	},
	534: &Race{
		ID:      534,
		Name:    "Weapon Rack",
		Neutral: "I00",
	},
	535: &Race{
		ID:      535,
		Name:    "Armor Rack",
		Neutral: "I01",
	},
	536: &Race{
		ID:      536,
		Name:    "Honey Pot",
		Neutral: "I02",
	},
	537: &Race{
		ID:      537,
		Name:    "Jum Jum Bucket",
		Neutral: "I03",
	},
	538: &Race{
		ID:      538,
		Name:    "Toolbox",
		Neutral: "I04",
	},
	539: &Race{
		ID:      539,
		Name:    "Stone Jug",
		Neutral: "I05",
	},
	540: &Race{
		ID:      540,
		Name:    "Small Plant",
		Neutral: "I06",
	},
	541: &Race{
		ID:      541,
		Name:    "Medium Plant",
		Neutral: "I07",
	},
	542: &Race{
		ID:      542,
		Name:    "Tall Plant",
		Neutral: "I08",
	},
	543: &Race{
		ID:      543,
		Name:    "Wine Cask",
		Neutral: "I09",
	},
	544: &Race{
		ID:      544,
		Name:    "Elven Boat",
		Neutral: "B01",
	},
	545: &Race{
		ID:      545,
		Name:    "Gnomish Boat",
		Neutral: "B02",
	},
	546: &Race{
		ID:      546,
		Name:    "Barrel Barge Ship",
		Neutral: "B03",
	},
	547: &Race{
		ID:      547,
		Name:    "Goo",
		Neutral: "GUL",
	},
	548: &Race{
		ID:      548,
		Name:    "Goo",
		Neutral: "GUM",
	},
	549: &Race{
		ID:      549,
		Name:    "Goo",
		Neutral: "GUS",
	},
	550: &Race{
		ID:      550,
		Name:    "Merchant Ship",
		Neutral: "B04",
	},
	551: &Race{
		ID:      551,
		Name:    "Pirate Ship",
		Neutral: "B05",
	},
	552: &Race{
		ID:      552,
		Name:    "Ghost Ship",
		Neutral: "B06",
	},
	553: &Race{
		ID:      553,
		Name:    "Banner",
		Neutral: "G00",
	},
	554: &Race{
		ID:      554,
		Name:    "Banner",
		Neutral: "G01",
	},
	555: &Race{
		ID:      555,
		Name:    "Banner",
		Neutral: "G02",
	},
	556: &Race{
		ID:      556,
		Name:    "Banner",
		Neutral: "G03",
	},
	557: &Race{
		ID:      557,
		Name:    "Banner",
		Neutral: "G04",
	},
	558: &Race{
		ID:      558,
		Name:    "Aviak",
		Neutral: "AVK",
	},
	559: &Race{
		ID:      559,
		Name:    "Beetle",
		Neutral: "BTL",
	},
	560: &Race{
		ID:      560,
		Name:    "Gorilla",
		Neutral: "GRL",
	},
	561: &Race{
		ID:      561,
		Name:    "Kedge",
		Neutral: "KDG",
	},
	562: &Race{
		ID:     562,
		Name:   "Kerran",
		Male:   "KRM",
		Female: "KRF",
	},
	563: &Race{
		ID:      563,
		Name:    "Shissar",
		Neutral: "SHS",
	},
	564: &Race{
		ID:      564,
		Name:    "Siren",
		Neutral: "SIN",
	},
	565: &Race{
		ID:      565,
		Name:    "Sphinx",
		Neutral: "SPX",
	},
	566: &Race{
		ID:     566,
		Name:   "Human",
		Male:   "HNM",
		Female: "HNF",
	},
	567: &Race{
		ID:      567,
		Name:    "Campfire",
		Neutral: "I10",
	},
	568: &Race{
		ID:     568,
		Name:   "Brownie",
		Male:   "BNM",
		Female: "BNF",
	},
	569: &Race{
		ID:      569,
		Name:    "Dragon",
		Neutral: "DRP",
	},
	570: &Race{
		ID:      570,
		Name:    "Exoskeleton",
		Neutral: "EXO",
	},
	571: &Race{
		ID:      571,
		Name:    "Ghoul",
		Neutral: "GHO",
	},
	572: &Race{
		ID:      572,
		Name:    "Clockwork Guardian",
		Neutral: "GUA",
	},
	573: &Race{
		ID:      573,
		Name:    "Mantrap",
		Neutral: "MTP",
	},
	574: &Race{
		ID:      574,
		Name:    "Minotaur",
		Neutral: "MTR",
	},
	575: &Race{
		ID:      575,
		Name:    "Scarecrow",
		Neutral: "SCC",
	},
	576: &Race{
		ID:      576,
		Name:    "Shade",
		Neutral: "SHE",
	},
	577: &Race{
		ID:      577,
		Name:    "Rotocopter",
		Neutral: "SWC",
	},
	578: &Race{
		ID:      578,
		Name:    "Tentacle Terror",
		Neutral: "TNT",
	},
	579: &Race{
		ID:      579,
		Name:    "Wereorc",
		Neutral: "WOK",
	},
	580: &Race{
		ID:      580,
		Name:    "Worg",
		Neutral: "WOR",
	},
	581: &Race{
		ID:      581,
		Name:    "Wyvern",
		Neutral: "WYR",
	},
	582: &Race{
		ID:      582,
		Name:    "Chimera",
		Neutral: "MCH",
	},
	583: &Race{
		ID:      583,
		Name:    "Kirin",
		Neutral: "MKI",
	},
	584: &Race{
		ID:      584,
		Name:    "Puma",
		Neutral: "MPU",
	},
	585: &Race{
		ID:      585,
		Name:    "Boulder",
		Neutral: "I11",
	},
	586: &Race{
		ID:      586,
		Name:    "Banner",
		Neutral: "G05",
	},
	587: &Race{
		ID:     587,
		Name:   "Elven Ghost",
		Male:   "XEM",
		Female: "XEF",
	},
	588: &Race{
		ID:     588,
		Name:   "Human Ghost",
		Male:   "XHM",
		Female: "XHF",
	},
	589: &Race{
		ID:      589,
		Name:    "Chest",
		Neutral: "I12",
	},
	590: &Race{
		ID:      590,
		Name:    "Chest",
		Neutral: "I13",
	},
	591: &Race{
		ID:      591,
		Name:    "Crystal",
		Neutral: "I14",
	},
	592: &Race{
		ID:      592,
		Name:    "Coffin",
		Neutral: "I15",
	},
	593: &Race{
		ID:      593,
		Name:    "Guardian CPU",
		Neutral: "I16",
	},
	594: &Race{
		ID:      594,
		Name:    "Worg",
		Neutral: "MWO",
	},
	595: &Race{
		ID:      595,
		Name:    "Mansion",
		Neutral: "OBJ_BLIMP",
	},
	596: &Race{
		ID:      596,
		Name:    "Floating Island",
		Neutral: "OBP__MELDRATH",
	},
	597: &Race{
		ID:      597,
		Name:    "Cragslither",
		Neutral: "MCS",
	},
	598: &Race{
		ID:      598,
		Name:    "Wrulon",
		Neutral: "MWR",
	},
	599: &Race{
		ID:      599,
		Name:    "Spell Particle 1",
		Neutral: "S01",
	},
	600: &Race{
		ID:     600,
		Name:   "Invisible Man of Zomm",
		Male:   "IVM",
		Female: "IVF",
	},
	601: &Race{
		ID:      601,
		Name:    "Robocopter of Zomm",
		Neutral: "SWC",
	},
	602: &Race{
		ID:      602,
		Name:    "Burynai",
		Neutral: "BUR",
	},
	603: &Race{
		ID:      603,
		Name:    "Frog",
		Neutral: "FGG",
	},
	604: &Race{
		ID:      604,
		Name:    "Dracolich",
		Neutral: "DRL",
	},
	605: &Race{
		ID:      605,
		Name:    "Iksar Ghost",
		Neutral: "XIM",
	},
	606: &Race{
		ID:      606,
		Name:    "Iksar Skeleton",
		Neutral: "SKI",
	},
	607: &Race{
		ID:      607,
		Name:    "Mephit",
		Neutral: "MPH",
	},
	608: &Race{
		ID:      608,
		Name:    "Muddite",
		Neutral: "MUD",
	},
	609: &Race{
		ID:      609,
		Name:    "Raptor",
		Neutral: "RPT",
	},
	610: &Race{
		ID:      610,
		Name:    "Sarnak",
		Neutral: "SRK",
	},
	611: &Race{
		ID:      611,
		Name:    "Scorpion",
		Neutral: "SCO",
	},
	612: &Race{
		ID:      612,
		Name:    "Tsetsian",
		Neutral: "TSE",
	},
	613: &Race{
		ID:      613,
		Name:    "Wurm",
		Neutral: "WRM",
	},
	614: &Race{
		ID:      614,
		Name:    "Nekhon",
		Neutral: "BAL",
	},
	615: &Race{
		ID:      615,
		Name:    "Hydra Crystal",
		Neutral: "HYC",
	},
	616: &Race{
		ID:      616,
		Name:    "Crystal Sphere",
		Neutral: "CRY",
	},
	617: &Race{
		ID:      617,
		Name:    "Gnoll",
		Neutral: "GND",
	},
	618: &Race{
		ID:      618,
		Name:    "Sokokar",
		Neutral: "SOK",
	},
	619: &Race{
		ID:      619,
		Name:    "Stone Pylon",
		Neutral: "PYS",
	},
	620: &Race{
		ID:      620,
		Name:    "Demon Vulture",
		Neutral: "DVL",
	},
	621: &Race{
		ID:      621,
		Name:    "Wagon",
		Neutral: "I17",
	},
	622: &Race{
		ID:      622,
		Name:    "God of Discord",
		Neutral: "GOD",
	},
	623: &Race{
		ID:      623,
		Name:    "Feran Mount",
		Neutral: "MFR",
	},
	624: &Race{
		ID:     624,
		Name:   "Ogre NPC - Male",
		Male:   "ONM",
		Female: "ONF",
	},
	625: &Race{
		ID:      625,
		Name:    "Sokokar Mount",
		Neutral: "MSO",
	},
	626: &Race{
		ID:      626,
		Name:    "Giant (Rallosian mats)",
		Neutral: "GRA",
	},
	627: &Race{
		ID:      627,
		Name:    "Sokokar (w saddle)",
		Neutral: "MSO",
	},
	628: &Race{
		ID:      628,
		Name:    "10th Anniversary Banner",
		Neutral: "BNX",
	},
	629: &Race{
		ID:      629,
		Name:    "10th Anniversary Cake",
		Neutral: "CAK",
	},
	630: &Race{
		ID:      630,
		Name:    "Wine Cask",
		Neutral: "I18",
	},
	631: &Race{
		ID:      631,
		Name:    "Hydra Mount",
		Neutral: "MHY",
	},
	632: &Race{
		ID:      632,
		Name:    "Hydra NPC",
		Neutral: "HYD",
	},
	633: &Race{
		ID:      633,
		Name:    "Wedding Flowers",
		Neutral: "I19",
	},
	634: &Race{
		ID:      634,
		Name:    "Wedding Arbor",
		Neutral: "I20",
	},
	635: &Race{
		ID:      635,
		Name:    "Wedding Altar",
		Neutral: "I21",
	},
	636: &Race{
		ID:      636,
		Name:    "Powder Keg",
		Neutral: "I22",
	},
	637: &Race{
		ID:      637,
		Name:    "Apexus",
		Neutral: "APX",
	},
	638: &Race{
		ID:      638,
		Name:    "Bellikos",
		Neutral: "BEL",
	},
	639: &Race{
		ID:      639,
		Name:    "Brell's First Creation",
		Neutral: "BFC",
	},
	640: &Race{
		ID:      640,
		Name:    "Brell",
		Neutral: "BRE",
	},
	641: &Race{
		ID:      641,
		Name:    "Crystalskin Ambuloid",
		Neutral: "CAM",
	},
	642: &Race{
		ID:      642,
		Name:    "Cliknar Queen",
		Neutral: "CLQ",
	},
	643: &Race{
		ID:      643,
		Name:    "Cliknar Soldier",
		Neutral: "CLS",
	},
	644: &Race{
		ID:      644,
		Name:    "Cliknar Worker",
		Neutral: "CLW",
	},
	645: &Race{
		ID:     645,
		Name:   "Coldain",
		Male:   "CDM",
		Female: "CDF",
	},
	647: &Race{
		ID:      647,
		Name:    "Crystalskin Sessiloid",
		Neutral: "CSE",
	},
	648: &Race{
		ID:      648,
		Name:    "Genari",
		Neutral: "GEN",
	},
	649: &Race{
		ID:      649,
		Name:    "Gigyn",
		Neutral: "GIG",
	},
	650: &Race{
		ID:      650,
		Name:    "Greken - Young Adult",
		Neutral: "GYA",
	},
	651: &Race{
		ID:      651,
		Name:    "Greken - Young",
		Neutral: "GYO",
	},
	652: &Race{
		ID:      652,
		Name:    "Cliknar Mount",
		Neutral: "MCL",
	},
	653: &Race{
		ID:      653,
		Name:    "Telmira",
		Neutral: "TEL",
	},
	654: &Race{
		ID:      654,
		Name:    "Spider Mount",
		Neutral: "MTA",
	},
	655: &Race{
		ID:      655,
		Name:    "Bear Mount",
		Neutral: "MBR",
	},
	656: &Race{
		ID:      656,
		Name:    "Rat Mount",
		Neutral: "MCR",
	},
	657: &Race{
		ID:      657,
		Name:    "Sessiloid Mount",
		Neutral: "MSD",
	},
	658: &Race{
		ID:      658,
		Name:    "Morell Thule",
		Neutral: "LTH",
	},
	659: &Race{
		ID:      659,
		Name:    "Marionette",
		Neutral: "MRT",
	},
	660: &Race{
		ID:      660,
		Name:    "Book Dervish",
		Neutral: "BKD",
	},
	661: &Race{
		ID:      661,
		Name:    "Topiary Lion",
		Neutral: "TPL",
	},
	662: &Race{
		ID:      662,
		Name:    "Rotdog",
		Neutral: "RDG",
	},
	663: &Race{
		ID:      663,
		Name:    "Amygdalan",
		Neutral: "AMY",
	},
	664: &Race{
		ID:      664,
		Name:    "Sandman",
		Neutral: "SND",
	},
	665: &Race{
		ID:      665,
		Name:    "Grandfather Clock",
		Neutral: "GFC",
	},
	666: &Race{
		ID:      666,
		Name:    "Gingerbread Man",
		Neutral: "GBM",
	},
	667: &Race{
		ID:     667,
		Name:   "Royal Guard",
		Male:   "BFR",
		Female: "BFF",
	},
	668: &Race{
		ID:      668,
		Name:    "Rabbit",
		Neutral: "BNY",
	},
	669: &Race{
		ID:      669,
		Name:    "Blind Dreamer",
		Neutral: "BDR",
	},
	670: &Race{
		ID:      670,
		Name:    "Cazic Thule",
		Neutral: "CTH",
	},
	671: &Race{
		ID:      671,
		Name:    "Topiary Lion Mount",
		Neutral: "MTL",
	},
	672: &Race{
		ID:      672,
		Name:    "Rot Dog Mount",
		Neutral: "MRD",
	},
	673: &Race{
		ID:      673,
		Name:    "Goral Mount",
		Neutral: "MGL",
	},
	674: &Race{
		ID:      674,
		Name:    "Selyrah Mount",
		Neutral: "MSL",
	},
	675: &Race{
		ID:      675,
		Name:    "Sclera Mount",
		Neutral: "MSC",
	},
	676: &Race{
		ID:      676,
		Name:    "Braxi Mount",
		Neutral: "MBX",
	},
	677: &Race{
		ID:      677,
		Name:    "Kangon Mount",
		Neutral: "MKG",
	},
	678: &Race{
		ID:   678,
		Name: "Erudite",
		Male: "ERU",
	},
	679: &Race{
		ID:      679,
		Name:    "Wurm Mount",
		Neutral: "MWM",
	},
	680: &Race{
		ID:      680,
		Name:    "Raptor Mount",
		Neutral: "MRP",
	},
	681: &Race{
		ID:      681,
		Name:    "Invisible Man",
		Neutral: "INV",
	},
	682: &Race{
		ID:      682,
		Name:    "Whirligig",
		Neutral: "MWI",
	},
	683: &Race{
		ID:      683,
		Name:    "Gnomish Balloon",
		Neutral: "MBL",
	},
	684: &Race{
		ID:      684,
		Name:    "Gnomish Rocket Pack",
		Neutral: "MRK",
	},
	685: &Race{
		ID:      685,
		Name:    "Gnomish Hovering Transport",
		Neutral: "MHB",
	},
	686: &Race{
		ID:      686,
		Name:    "Selyrah",
		Neutral: "SEY",
	},
	687: &Race{
		ID:      687,
		Name:    "Goral",
		Neutral: "G}1",
	},
	688: &Race{
		ID:      688,
		Name:    "Braxi",
		Neutral: "BRX",
	},
	689: &Race{
		ID:      689,
		Name:    "Kangon",
		Neutral: "KNG",
	},
	690: &Race{
		ID:      690,
		Name:    "Invisible Man",
		Neutral: "I23",
	},
	691: &Race{
		ID:      691,
		Name:    "Floating Tower",
		Neutral: "B07",
	},
	692: &Race{
		ID:      692,
		Name:    "Explosive Cart",
		Neutral: "B08",
	},
	693: &Race{
		ID:      693,
		Name:    "Blimp Ship",
		Neutral: "B09",
	},
	694: &Race{
		ID:      694,
		Name:    "Tumbleweed",
		Neutral: "I24",
	},
	695: &Race{
		ID:      695,
		Name:    "Alaran",
		Neutral: "ALA",
	},
	696: &Race{
		ID:      696,
		Name:    "Swinetor",
		Neutral: "SWI",
	},
	697: &Race{
		ID:      697,
		Name:    "Triumvirate",
		Neutral: "TRG",
	},
	698: &Race{
		ID:      698,
		Name:    "Hadal",
		Neutral: "HDL",
	},
	699: &Race{
		ID:      699,
		Name:    "Hovering Platform",
		Neutral: "B10",
	},
	700: &Race{
		ID:      700,
		Name:    "Parasitic Scavenger",
		Neutral: "PSC",
	},
	701: &Race{
		ID:      701,
		Name:    "Grendlaen",
		Neutral: "GRD",
	},
	702: &Race{
		ID:      702,
		Name:    "Ship in a Bottle",
		Neutral: "I25",
	},
	703: &Race{
		ID:      703,
		Name:    "Alaran Sentry Stone",
		Neutral: "I26",
	},
	704: &Race{
		ID:      704,
		Name:    "Dervish",
		Neutral: "SDV",
	},
	705: &Race{
		ID:      705,
		Name:    "Regeneration Pool",
		Neutral: "I27",
	},
	706: &Race{
		ID:      706,
		Name:    "Teleportation Stand",
		Neutral: "I28",
	},
	707: &Race{
		ID:      707,
		Name:    "Relic Case",
		Neutral: "I29",
	},
	708: &Race{
		ID:      708,
		Name:    "Alaran Ghost",
		Neutral: "ALG",
	},
	709: &Race{
		ID:      709,
		Name:    "Skystrider",
		Neutral: "MPG",
	},
	710: &Race{
		ID:      710,
		Name:    "Water Spout",
		Neutral: "I30",
	},
	711: &Race{
		ID:      711,
		Name:    "Aviak Pull Along",
		Neutral: "I31",
	},
	712: &Race{
		ID:      712,
		Name:    "Gelatinous Cube",
		Neutral: "GCB",
	},
	713: &Race{
		ID:      713,
		Name:    "Cat",
		Neutral: "CAT",
	},
	714: &Race{
		ID:      714,
		Name:    "Elk Head",
		Neutral: "I32",
	},
	715: &Race{
		ID:      715,
		Name:    "Holgresh",
		Neutral: "HLG",
	},
	716: &Race{
		ID:      716,
		Name:    "Beetle",
		Neutral: "BTS",
	},
	717: &Race{
		ID:      717,
		Name:    "Vine Maw",
		Neutral: "VNM",
	},
	718: &Race{
		ID:      718,
		Name:    "Ratman",
		Neutral: "CHT",
	},
	719: &Race{
		ID:      719,
		Name:    "Fallen Knight",
		Neutral: "FKN",
	},
	720: &Race{
		ID:      720,
		Name:    "Flying Carpet",
		Neutral: "MCP",
	},
	721: &Race{
		ID:      721,
		Name:    "Carrier Hand",
		Neutral: "MRH",
	},
	722: &Race{
		ID:     722,
		Name:   "Akheva",
		Male:   "AHM",
		Female: "AHF",
	},
	723: &Race{
		ID:   723,
		Name: "Servant of Shadow",
		Male: "SOS",
	},
	724: &Race{
		ID:     724,
		Name:   "Luclin",
		Female: "LUC",
	},
	725: &Race{
		ID:      725,
		Name:    "Xaric the Unspoken",
		Neutral: "AXA",
	},
	726: &Race{
		ID:      726,
		Name:    "Dervish (Ver. 5)",
		Neutral: "HDV",
	},
	727: &Race{
		ID:      727,
		Name:    "Dervish (Ver. 6)",
		Neutral: "DV6",
	},
	728: &Race{
		ID:      728,
		Name:    "God - Luclin (Ver. 2)",
		Neutral: "LU2",
	},
	729: &Race{
		ID:      729,
		Name:    "God - Luclin (Ver. 3)",
		Neutral: "LU3",
	},
	730: &Race{
		ID:      730,
		Name:    "Orb",
		Neutral: "ORB",
	},
	731: &Race{
		ID:      731,
		Name:    "God - Luclin (Ver. 4)",
		Neutral: "LU4",
	},
	732: &Race{
		ID:      732,
		Name:    "Pegasus",
		Neutral: "PG3",
	},
	2253: &Race{
		ID:      2253,
		Name:    "(null)",
		Male:    "PPOINT",
		Female:  "PPOINT",
		Neutral: "PPOINT",
	},
	2254: &Race{
		ID:      2254,
		Name:    "(null)",
		Male:    "PPOINT",
		Female:  "PPOINT",
		Neutral: "PPOINT",
	},
	2255: &Race{
		ID:      2255,
		Name:    "(null)",
		Male:    "PPOINT",
		Female:  "PPOINT",
		Neutral: "PPOINT",
	},
	2256: &Race{
		ID:      2256,
		Name:    "(null)",
		Male:    "PPOINT",
		Female:  "PPOINT",
		Neutral: "PPOINT",
	},
	2257: &Race{
		ID:      2257,
		Name:    "(null)",
		Male:    "PPOINT",
		Female:  "PPOINT",
		Neutral: "PPOINT",
	},
	2258: &Race{
		ID:      2258,
		Name:    "(null)",
		Male:    "PPOINT",
		Female:  "PPOINT",
		Neutral: "PPOINT",
	},
	2259: &Race{
		ID:      2259,
		Name:    "(null)",
		Male:    "ARROW",
		Female:  "ARROW",
		Neutral: "ARROW",
	},
}
