version: '3'
services:
  mariadb:
    image: "bitnami/mariadb:latest"
    volumes:
      - ./docker/db:/bitnami/mariadb
    environment:      
      MARIADB_DATABASE: eqemu
      MARIADB_USER: eqemu
      MARIADB_PASSWORD: eqemu
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    expose:
      - "3306"
