/* 
 * Xegony API
 *
 * Endpoints of the Xegony Editor for the Everquest Emulator (EQEMU)
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ErrorUnexpected struct {

	Code int32 `json:"code"`

	Message string `json:"message"`
}
