/**
 * Xegony API
 * generic description goes here
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PbNpc {
    ID?: string;

    name?: string;

    lastName?: string;

    level?: string;

    raceID?: string;

    classID?: string;

    bodyTypeID?: string;

    hitpoints?: string;

    mana?: string;

    gender?: string;

    texture?: string;

    helmTexture?: string;

    herosForgeModel?: string;

    size?: number;

    hpRegenRate?: string;

    manaRegenRate?: string;

    lootID?: string;

    merchantID?: string;

    altCurrencyID?: string;

    npcSpellsID?: string;

    npcSpellsEffectsID?: string;

    npcFactionID?: string;

    adventureTemplateID?: string;

    trapTemplate?: string;

    mininumDamage?: string;

    maximumDamage?: string;

    attackCount?: string;

    npcSpecialAttacks?: string;

    specialAbilitiesRaw?: string;

    aggroRadius?: string;

    assistRadius?: string;

    face?: string;

    luclinHairStyle?: string;

    luclinHairColor?: string;

    luclinEyeColor?: string;

    luclinEyeColor2?: string;

    luclinBeardColor?: string;

    luclinBeard?: string;

    drakkinHeritage?: string;

    drakkinTattoo?: string;

    drakkinDetails?: string;

    armorTintID?: string;

    armorTintRed?: string;

    armorTintGreen?: string;

    armorTintBlue?: string;

    dMeleeTexture1?: string;

    dMeleeTexture2?: string;

    ammoIDFile?: string;

    primaryMeleeTypeID?: string;

    secondaryMeleeTypeID?: string;

    rangedTypeID?: string;

    runspeed?: number;

    magicResistance?: string;

    coldResistance?: string;

    diseaseResistance?: string;

    fireResistance?: string;

    poisonResistance?: string;

    corruptionResistance?: string;

    physicalResistance?: string;

    seeInvisible?: string;

    seeInvisibleUndead?: string;

    questGlobal?: string;

    armorClass?: string;

    npcAggro?: string;

    spawnLimit?: string;

    attackSpeed?: number;

    attackDelay?: string;

    findable?: string;

    strength?: string;

    stamina?: string;

    dexterity?: string;

    agility?: string;

    intelligence?: string;

    wisdom?: string;

    charisma?: string;

    seeHide?: string;

    seeImprovedHide?: string;

    trackable?: string;

    isBot?: string;

    exclude?: string;

    attack?: string;

    accuracy?: string;

    avoidance?: string;

    slowMitigation?: string;

    version?: string;

    maxLevel?: string;

    scaleRate?: string;

    privateCorpse?: string;

    uniqueSpawnByName?: string;

    underwater?: string;

    isQuest?: string;

    emoteID?: string;

    spellScale?: number;

    healScale?: number;

    noTargetHotkey?: string;

    raidTarget?: string;

    armTexture?: string;

    bracerTexture?: string;

    handTexture?: string;

    legTexture?: string;

    feetTexture?: string;

    light?: string;

    walkSpeed?: string;

    peqID?: string;

    unique?: string;

    fixed?: string;

    ignoreDespawn?: string;

    showName?: string;

    untargetable?: string;

    race?: models.PbRace;

    _class?: models.PbClass;

    cleanName?: string;

}
