package file

import (
	"github.com/xackery/xegony/model"
)

func loadDeityDefault() model.Deitys {
	return model.Deitys{
		{
			SpellID:   0,
			Name:      "Agnostic",
			ShortName: "Agnostic",
			Icon:      "xa-shield",
			ID:        140,
			Bit:       1,
		},
		{
			SpellID:   1,
			Name:      "Bertoxxulous",
			ShortName: "Bertoxxulous",
			Icon:      "xa-shield",
			ID:        201,
			Bit:       2,
		},
		{
			SpellID:   2,
			Name:      "Brell Serilis",
			ShortName: "Brell Serilis",
			Icon:      "xa-shield",
			ID:        202,
			Bit:       4,
		},
		{
			SpellID:   3,
			Name:      "Cazic Thule",
			ShortName: "Cazic Thule",
			Icon:      "xa-shield",
			ID:        203,
			Bit:       8,
		},
		{
			SpellID:   4,
			Name:      "Erollsi Marr",
			ShortName: "Erollsi Marr",
			Icon:      "xa-shield",
			ID:        204,
			Bit:       16,
		},
		{
			SpellID:   5,
			Name:      "Bristlebane",
			ShortName: "Bristlebane",
			Icon:      "xa-shield",
			ID:        205,
			Bit:       32,
		},
		{
			SpellID:   6,
			Name:      "Innoruuk",
			ShortName: "Innoruuk",
			Icon:      "xa-shield",
			ID:        206,
			Bit:       64,
		},
		{
			SpellID:   7,
			Name:      "Karana",
			ShortName: "Karana",
			Icon:      "xa-shield",
			ID:        207,
			Bit:       128,
		},
		{
			SpellID:   8,
			Name:      "Mithaniel Marr",
			ShortName: "Mithaniel Marr",
			Icon:      "xa-shield",
			ID:        208,
			Bit:       256,
		},
		{
			SpellID:   9,
			Name:      "Prexus",
			ShortName: "Prexus",
			Icon:      "xa-shield",
			ID:        209,
			Bit:       512,
		},
		{
			SpellID:   10,
			Name:      "Quellious",
			ShortName: "Quellious",
			Icon:      "xa-shield",
			ID:        210,
			Bit:       1024,
		},
		{
			SpellID:   11,
			Name:      "Rallos Zek",
			ShortName: "Rallos Zek",
			Icon:      "xa-shield",
			ID:        211,
			Bit:       2048,
		},
		{
			SpellID:   12,
			Name:      "Rodcet Nife",
			ShortName: "Rodcet Nife",
			Icon:      "xa-shield",
			ID:        212,
			Bit:       4096,
		},
		{
			SpellID:   13,
			Name:      "Solusek Ro",
			ShortName: "Solusek Ro",
			Icon:      "xa-shield",
			ID:        213,
			Bit:       8192,
		},
		{
			SpellID:   14,
			Name:      "The Tribunal",
			ShortName: "The Tribunal",
			Icon:      "xa-shield",
			ID:        214,
			Bit:       16384,
		},
		{
			SpellID:   15,
			Name:      "Tunare",
			ShortName: "Tunare",
			Icon:      "xa-shield",
			ID:        215,
			Bit:       32768,
		},
		{
			SpellID:   16,
			Name:      "Veeshan",
			ShortName: "Veeshan",
			Icon:      "xa-shield",
			ID:        216,
			Bit:       65536,
		},
	}
}
