package file

import (
	"github.com/xackery/xegony/model"
)

func loadRaceDefault() model.Races {
	return model.Races{
		{
			ID:     1,
			Name:   "Human",
			Male:   "HUM",
			Female: "HUF",
			Icon:   "xa-player",
		},
		{
			ID:     2,
			Name:   "Barbarian",
			Male:   "BAM",
			Female: "BAF",
			Icon:   "xa-fox",
		},

		{
			ID:     3,
			Name:   "Erudite",
			Male:   "ERM",
			Female: "ERF",
			Icon:   "xa-book",
		},
		{
			ID:     4,
			Name:   "Wood Elf",
			Male:   "ELM",
			Female: "ELF",
			Icon:   "xa-pine-tree",
		},
		{
			ID:     5,
			Name:   "High Elf",
			Male:   "HIM",
			Female: "HIF",
			Icon:   "xa-tesla",
		},
		{
			ID:     6,
			Name:   "Dark Elf",
			Male:   "DAM",
			Female: "DAF",
			Icon:   "xa-bleeding-eye",
		},
		{
			ID:     7,
			Name:   "Half Elf",
			Male:   "HAM",
			Female: "HAF",
			Icon:   "xa-aware",
		},
		{
			ID:     8,
			Name:   "Dwarf",
			Male:   "DWM",
			Female: "DWF",
			Icon:   "xa-beer",
		},
		{
			ID:     9,
			Name:   "Troll",
			Male:   "TRM",
			Female: "TRF",
			Icon:   "xa-bird-mask",
		},
		{
			ID:     10,
			Name:   "Ogre",
			Male:   "OGM",
			Female: "OGF",
			Icon:   "xa-muscle-fat",
		},
		{
			ID:     11,
			Name:   "Halfling",
			Male:   "HOM",
			Female: "HOF",
			Icon:   "xa-footprint",
		},
		{
			ID:     12,
			Name:   "Gnome",
			Male:   "GNM",
			Female: "GNF",
			Icon:   "xa-gears",
		},
		{
			ID:      13,
			Name:    "Aviak",
			Neutral: "AVI",
		},
		{
			ID:      14,
			Name:    "Werewolf",
			Neutral: "WER",
		},
		{
			ID:     15,
			Name:   "Brownie",
			Male:   "BRM",
			Female: "BRF",
		},
		{
			ID:      16,
			Name:    "Centaur",
			Male:    "CEM",
			Female:  "CEF",
			Neutral: "CEN",
		},
		{
			ID:      17,
			Name:    "Golem",
			Male:    "GOM",
			Female:  "GOF",
			Neutral: "GOL",
		},
		{
			ID:      18,
			Name:    "Giant",
			Neutral: "GIA",
		},
		{
			ID:      19,
			Name:    "Trakanon",
			Neutral: "TRK",
		},
		{
			ID:      20,
			Name:    "Venril Sathir",
			Neutral: "VST",
		},
		{
			ID:      21,
			Name:    "Evil Eye",
			Neutral: "BEH",
		},
		{
			ID:      22,
			Name:    "Beetle",
			Neutral: "BET",
		},
		{
			ID:     23,
			Name:   "Kerran",
			Male:   "CPM",
			Female: "CPF",
		},
		{
			ID:      24,
			Name:    "Fish",
			Neutral: "FIS",
		},

		{
			ID:     25,
			Name:   "Fairy",
			Male:   "FAM",
			Female: "FAF",
		},
		{
			ID:      26,
			Name:    "Froglok",
			Neutral: "FRO",
			Icon:    "xa-water-drop",
		},
		{
			ID:      27,
			Name:    "Froglok",
			Neutral: "FRG",
		},
		{
			ID:      28,
			Name:    "Fungusman",
			Neutral: "FUN",
		},
		{
			ID:      29,
			Name:    "Gargoyle",
			Male:    "GAM",
			Neutral: "GAR",
		},
		{
			ID:      30,
			Name:    "Gasbag",
			Neutral: "BEH",
		},
		{
			ID:      31,
			Name:    "Gelatinous Cube",
			Neutral: "CUB",
		},
		{
			ID:     32,
			Name:   "Ghost",
			Male:   "GHM",
			Female: "GHF",
		},
		{
			ID:      33,
			Name:    "Ghoul",
			Neutral: "GHU",
		},
		{
			ID:      34,
			Name:    "Bat",
			Neutral: "BAT",
		},
		{
			ID:      36,
			Name:    "Rat",
			Neutral: "RAT",
		},
		{
			ID:      37,
			Name:    "Snake",
			Neutral: "SNA",
		},
		{
			ID:      38,
			Name:    "Spider",
			Neutral: "SPI",
		},
		{
			ID:      39,
			Name:    "Gnoll",
			Neutral: "GNN",
		},
		{
			ID:      40,
			Name:    "Goblin",
			Neutral: "GOB",
		},
		{
			ID:      41,
			Name:    "Gorilla",
			Neutral: "GOR",
		},
		{
			ID:      42,
			Name:    "Wolf",
			Male:    "WOM",
			Female:  "WOF",
			Neutral: "WOL",
		},
		{
			ID:      43,
			Name:    "Bear",
			Neutral: "BEA",
		},
		{
			ID:     44,
			Name:   "Guard",
			Male:   "FPM",
			Female: "FPF",
		},
		{
			ID:      45,
			Name:    "Demi Lich",
			Neutral: "DML",
		},
		{
			ID:      46,
			Name:    "Imp",
			Neutral: "IMP",
		},
		{
			ID:      47,
			Name:    "Griffin",
			Neutral: "GRI",
		},
		{
			ID:      48,
			Name:    "Kobold",
			Neutral: "KOB",
		},
		{
			ID:      49,
			Name:    "Dragon",
			Neutral: "DRA",
			Icon:    "xa-wyvern",
		},
		{
			ID:     50,
			Name:   "Lion",
			Male:   "LIM",
			Female: "LIF",
		},
		{
			ID:      51,
			Name:    "Lizard Man",
			Neutral: "LIZ",
		},
		{
			ID:     52,
			Name:   "Mimic",
			Male:   "MIM",
			Female: "MIF",
		},
		{
			ID:      53,
			Name:    "Minotaur",
			Neutral: "MIN",
		},
		{
			ID:      54,
			Name:    "Orc",
			Neutral: "ORC",
		},
		{
			ID:     55,
			Name:   "Beggar",
			Male:   "BGM",
			Female: "BGF",
		},
		{
			ID:     56,
			Name:   "Pixie",
			Male:   "PIM",
			Female: "PIF",
		},
		{
			ID:     57,
			Name:   "Drachnid",
			Male:   "DRM",
			Female: "DRF",
		},
		{
			ID:      58,
			Name:    "Solusek Ro",
			Neutral: "SOL",
		},
		{
			ID:      59,
			Name:    "Goblin",
			Neutral: "BGG",
		},
		{
			ID:      60,
			Name:    "Skeleton",
			Neutral: "SKE",
		},
		{
			ID:      61,
			Name:    "Shark",
			Neutral: "SHA",
		},
		{
			ID:      62,
			Name:    "Tunare",
			Neutral: "TUN",
		},
		{
			ID:      63,
			Name:    "Tiger",
			Neutral: "TIG",
		},
		{
			ID:      64,
			Name:    "Treant",
			Neutral: "TRE",
		},
		{
			ID:     65,
			Name:   "Vampire",
			Male:   "DVM",
			Female: "DVF",
		},
		{
			ID:      66,
			Name:    "Rallos Zek",
			Neutral: "RAL",
		},
		{
			ID:     67,
			Name:   "Human",
			Male:   "HHM",
			Female: "HHF",
		},
		{
			ID:      68,
			Name:    "Tentacle Terror",
			Male:    "TEM",
			Female:  "TEF",
			Neutral: "TEN",
		},
		{
			ID:      69,
			Name:    "Will-O-Wisp",
			Neutral: "WIL",
		},
		{
			ID:     70,
			Name:   "Zombie",
			Male:   "ZOM",
			Female: "ZOF",
		},
		{
			ID:     71,
			Name:   "Human",
			Male:   "QCM",
			Female: "QCF",
		},
		{
			ID:      72,
			Name:    "Ship",
			Male:    "SHIP",
			Female:  "PRE",
			Neutral: "PRE",
		},
		{
			ID:      73,
			Name:    "Launch",
			Male:    "LAUNCHM",
			Neutral: "LAUNCH",
		},
		{
			ID:      74,
			Name:    "Piranha",
			Neutral: "PIR",
		},
		{
			ID:      75,
			Name:    "Elemental",
			Neutral: "ELE",
		},
		{
			ID:      76,
			Name:    "Puma",
			Neutral: "PUM",
		},
		{
			ID:     77,
			Name:   "Dark Elf",
			Male:   "NGM",
			Female: "NGF",
		},
		{
			ID:     78,
			Name:   "Erudite",
			Male:   "EGM",
			Female: "EGF",
		},
		{
			ID:      79,
			Name:    "Bixie",
			Neutral: "BIX",
		},
		{
			ID:      80,
			Name:    "Reanimated Hand",
			Neutral: "REA",
		},
		{
			ID:     81,
			Name:   "Halfling",
			Male:   "RIM",
			Female: "RIF",
		},
		{
			ID:      82,
			Name:    "Scarecrow",
			Neutral: "SCA",
		},
		{
			ID:      83,
			Name:    "Skunk",
			Neutral: "SKU",
		},
		{
			ID:      84,
			Name:    "Snake Elemental",
			Neutral: "SNE",
		},
		{
			ID:      85,
			Name:    "Spectre",
			Neutral: "SPE",
		},
		{
			ID:      86,
			Name:    "Sphinx",
			Neutral: "SPH",
		},
		{
			ID:      87,
			Name:    "Armadillo",
			Neutral: "ARM",
		},
		{
			ID:      88,
			Name:    "Clockwork Gnome",
			Male:    "CLM",
			Female:  "CLF",
			Neutral: "CLN",
		},
		{
			ID:      89,
			Name:    "Drake",
			Neutral: "DRK",
		},
		{
			ID:     90,
			Name:   "Barbarian",
			Male:   "HLM",
			Female: "HLF",
		},
		{
			ID:      91,
			Name:    "Alligator",
			Neutral: "ALL",
		},
		{
			ID:     92,
			Name:   "Troll",
			Male:   "GRM",
			Female: "GRF",
		},
		{
			ID:     93,
			Name:   "Ogre",
			Male:   "OKM",
			Female: "OKF",
		},
		{
			ID:      94,
			Name:    "Dwarf",
			Male:    "KAM",
			Female:  "KAF",
			Neutral: "KAN",
		},
		{
			ID:      95,
			Name:    "Cazic Thule",
			Neutral: "CAZ",
		},
		{
			ID:      96,
			Name:    "Cockatrice",
			Neutral: "COC",
		},
		{
			ID:      97,
			Name:    "Daisy Man",
			Neutral: "DIA",
		},
		{
			ID:     98,
			Name:   "Vampire",
			Male:   "VSM",
			Female: "VSF",
		},
		{
			ID:      99,
			Name:    "Amygdalan",
			Neutral: "DEN",
		},
		{
			ID:      100,
			Name:    "Dervish",
			Neutral: "DER",
		},
		{
			ID:      101,
			Name:    "Efreeti",
			Neutral: "EFR",
		},
		{
			ID:      102,
			Name:    "Tadpole",
			Neutral: "FRT",
		},
		{
			ID:      103,
			Name:    "Kedge",
			Neutral: "KED",
		},
		{
			ID:      104,
			Name:    "Leech",
			Neutral: "LEE",
		},
		{
			ID:      105,
			Name:    "Swordfish",
			Neutral: "SWO",
		},
		{
			ID:     106,
			Name:   "Guard",
			Male:   "FEM",
			Female: "FEF",
		},
		{
			ID:      107,
			Name:    "Mammoth",
			Neutral: "MAM",
		},
		{
			ID:      108,
			Name:    "Eye",
			Neutral: "EYE",
		},
		{
			ID:      109,
			Name:    "Wasp",
			Neutral: "WAS",
		},
		{
			ID:      110,
			Name:    "Mermaid",
			Neutral: "MER",
		},
		{
			ID:      111,
			Name:    "Harpy",
			Neutral: "HAR",
		},
		{
			ID:     112,
			Name:   "Guard",
			Male:   "GFM",
			Female: "GFF",
		},
		{
			ID:      113,
			Name:    "Drixie",
			Neutral: "DRI",
		},
		{
			ID:      114,
			Name:    "Ghost Ship",
			Neutral: "GSP",
		},
		{
			ID:      115,
			Name:    "Clam",
			Neutral: "CLA",
		},
		{
			ID:      116,
			Name:    "Seahorse",
			Neutral: "SEA",
		},
		{
			ID:     117,
			Name:   "Ghost",
			Male:   "GDM",
			Female: "GDF",
		},
		{
			ID:     118,
			Name:   "Ghost",
			Male:   "GEM",
			Female: "GEF",
		},
		{
			ID:      119,
			Name:    "Saber-toothed Cat",
			Neutral: "STC",
		},
		{
			ID:      120,
			Name:    "Wolf",
			Neutral: "WOE",
		},
		{
			ID:      121,
			Name:    "Gorgon",
			Neutral: "GRG",
		},
		{
			ID:      122,
			Name:    "Dragon",
			Neutral: "DRU",
		},
		{
			ID:      123,
			Name:    "Innoruuk",
			Neutral: "INN",
		},
		{
			ID:      124,
			Name:    "Unicorn",
			Neutral: "UNI",
		},
		{
			ID:      125,
			Name:    "Pegasus",
			Neutral: "PEG",
		},
		{
			ID:      126,
			Name:    "Djinn",
			Neutral: "DJI",
		},
		{
			ID:     127,
			Name:   "Invisible Man",
			Male:   "IVM",
			Female: "IVF",
		},
		{
			ID:     128,
			Name:   "Iksar",
			Male:   "IKM",
			Female: "IKF",
			Icon:   "xa-gecko",
		},
		{
			ID:      129,
			Name:    "Scorpion",
			Neutral: "SCR",
		},
		{
			ID:     130,
			Name:   "Vah Shir",
			Male:   "KEM",
			Female: "KEF",
			Icon:   "xa-lion",
		},
		{
			ID:      131,
			Name:    "Sarnak",
			Neutral: "SRW",
		},
		{
			ID:      132,
			Name:    "Draglock",
			Neutral: "DLK",
		},
		{
			ID:      133,
			Name:    "Drolvarg",
			Neutral: "LYC",
		},
		{
			ID:      134,
			Name:    "Mosquito",
			Neutral: "MOS",
		},
		{
			ID:      135,
			Name:    "Rhinoceros",
			Neutral: "RHI",
		},
		{
			ID:      136,
			Name:    "Xalgoz",
			Neutral: "XAL",
		},
		{
			ID:      137,
			Name:    "Goblin",
			Neutral: "KGO",
		},
		{
			ID:      138,
			Name:    "Yeti",
			Neutral: "YET",
		},
		{
			ID:      139,
			Name:    "Iksar",
			Male:    "ICM",
			Female:  "ICF",
			Neutral: "ICN",
		},
		{
			ID:      140,
			Name:    "Giant",
			Neutral: "FGI",
		},
		{
			ID:      141,
			Name:    "Boat",
			Male:    "BOAT",
			Female:  "BOAT",
			Neutral: "BOAT",
		},
		{
			ID:      144,
			Name:    "Burynai",
			Neutral: "BRN",
		},
		{
			ID:      145,
			Name:    "Goo",
			Neutral: "GOO",
		},
		{
			ID:      146,
			Name:    "Sarnak Spirit",
			Neutral: "SSN",
		},
		{
			ID:     147,
			Name:   "Iksar Spirit",
			Male:   "SIM",
			Female: "SIF",
		},
		{
			ID:      148,
			Name:    "Fish",
			Neutral: "BAC",
		},
		{
			ID:      149,
			Name:    "Scorpion",
			Neutral: "ISC",
		},
		{
			ID:      150,
			Name:    "Erollisi",
			Neutral: "ERO",
		},
		{
			ID:      151,
			Name:    "Tribunal",
			Neutral: "TRI",
		},
		{
			ID:      152,
			Name:    "Bertoxxulous",
			Neutral: "BER",
		},
		{
			ID:      153,
			Name:    "Bristlebane",
			Neutral: "BRI",
		},
		{
			ID:      154,
			Name:    "Fay Drake",
			Neutral: "FDR",
		},
		{
			ID:      155,
			Name:    "Undead Sarnak",
			Neutral: "SSK",
		},
		{
			ID:      156,
			Name:    "Ratman",
			Neutral: "VRM",
		},
		{
			ID:      157,
			Name:    "Wyvern",
			Neutral: "WYV",
		},
		{
			ID:      158,
			Name:    "Wurm",
			Neutral: "WUR",
		},
		{
			ID:      159,
			Name:    "Devourer",
			Neutral: "DEV",
		},
		{
			ID:      160,
			Name:    "Iksar Golem",
			Neutral: "IKG",
		},
		{
			ID:      161,
			Name:    "Undead Iksar",
			Neutral: "IKS",
		},
		{
			ID:      162,
			Name:    "Man-Eating Plant",
			Neutral: "MEP",
		},
		{
			ID:      163,
			Name:    "Raptor",
			Neutral: "RAP",
		},
		{
			ID:      164,
			Name:    "Sarnak Golem",
			Neutral: "SGO",
		},
		{
			ID:      165,
			Name:    "Dragon",
			Neutral: "SED",
		},
		{
			ID:      166,
			Name:    "Animated Hand",
			Neutral: "IKH",
		},
		{
			ID:      167,
			Name:    "Succulent",
			Neutral: "SUC",
		},
		{
			ID:      168,
			Name:    "Holgresh",
			Neutral: "FMO",
		},
		{
			ID:      169,
			Name:    "Brontotherium",
			Neutral: "BTM",
		},
		{
			ID:      170,
			Name:    "Snow Dervish",
			Neutral: "SDE",
		},
		{
			ID:      171,
			Name:    "Dire Wolf",
			Neutral: "DIW",
		},
		{
			ID:      172,
			Name:    "Manticore",
			Neutral: "MTC",
		},
		{
			ID:      173,
			Name:    "Totem",
			Neutral: "TOT",
		},
		{
			ID:      174,
			Name:    "Ice Spectre",
			Neutral: "SPC",
		},
		{
			ID:      175,
			Name:    "Enchanted Armor",
			Neutral: "ENA",
		},
		{
			ID:      176,
			Name:    "Snow Rabbit",
			Neutral: "SBU",
		},
		{
			ID:      177,
			Name:    "Walrus",
			Neutral: "WAL",
		},
		{
			ID:      178,
			Name:    "Geonid",
			Neutral: "RGM",
		},
		{
			ID:      181,
			Name:    "Yakkar",
			Neutral: "YAK",
		},
		{
			ID:      182,
			Name:    "Faun",
			Neutral: "FAN",
		},
		{
			ID:      183,
			Name:    "Coldain",
			Male:    "COM",
			Female:  "COF",
			Neutral: "COK",
		},
		{
			ID:      184,
			Name:    "Dragon",
			Neutral: "DR2",
		},
		{
			ID:      185,
			Name:    "Hag",
			Neutral: "HAG",
		},
		{
			ID:      186,
			Name:    "Hippogriff",
			Neutral: "HIP",
		},
		{
			ID:      187,
			Name:    "Siren",
			Neutral: "SIR",
		},
		{
			ID:      188,
			Name:    "Giant",
			Neutral: "FSG",
		},
		{
			ID:      189,
			Name:    "Giant",
			Male:    "STM",
			Neutral: "STG",
		},
		{
			ID:      190,
			Name:    "Othmir",
			Neutral: "OTM",
		},
		{
			ID:      191,
			Name:    "Ulthork",
			Neutral: "WLM",
		},
		{
			ID:      192,
			Name:    "Dragon",
			Neutral: "CCD",
		},
		{
			ID:      193,
			Name:    "Abhorrent",
			Neutral: "ABH",
		},
		{
			ID:      194,
			Name:    "Sea Turtle",
			Neutral: "STU",
		},
		{
			ID:      195,
			Name:    "Dragon",
			Neutral: "BWD",
		},
		{
			ID:      196,
			Name:    "Dragon",
			Neutral: "GDR",
		},
		{
			ID:      197,
			Name:    "Ronnie Test",
			Neutral: "RON",
		},
		{
			ID:      198,
			Name:    "Dragon",
			Neutral: "PRI",
		},
		{
			ID:      199,
			Name:    "Shik'Nar",
			Neutral: "SKN",
		},
		{
			ID:      200,
			Name:    "Rockhopper",
			Neutral: "RHP",
		},
		{
			ID:      201,
			Name:    "Underbulk",
			Neutral: "UNB",
		},
		{
			ID:      202,
			Name:    "Grimling",
			Male:    "GMM",
			Female:  "GMF",
			Neutral: "GMN",
		},
		{
			ID:      203,
			Name:    "Worm",
			Neutral: "VAC",
		},
		{
			ID:      204,
			Name:    "Evan Test",
			Neutral: "ECS",
		},
		{
			ID:      205,
			Name:    "Shadel",
			Neutral: "KHA",
		},
		{
			ID:      206,
			Name:    "Owlbear",
			Neutral: "OWB",
		},
		{
			ID:      207,
			Name:    "Rhino Beetle",
			Neutral: "RNB",
		},
		{
			ID:     208,
			Name:   "Vampire",
			Male:   "VPM",
			Female: "VPF",
		},
		{
			ID:      209,
			Name:    "Earth Elemental",
			Neutral: "EEL",
		},
		{
			ID:      210,
			Name:    "Air Elemental",
			Neutral: "AEL",
		},
		{
			ID:      211,
			Name:    "Water Elemental",
			Neutral: "WEL",
		},
		{
			ID:      212,
			Name:    "Fire Elemental",
			Neutral: "FEL",
		},
		{
			ID:      213,
			Name:    "Wetfang Minnow",
			Neutral: "WET",
		},
		{
			ID:      214,
			Name:    "Thought Horror",
			Neutral: "THO",
		},
		{
			ID:      215,
			Name:    "Tegi",
			Neutral: "TEG",
		},
		{
			ID:      216,
			Name:    "Horse",
			Male:    "HSM",
			Female:  "HSF",
			Neutral: "HSN",
		},
		{
			ID:      217,
			Name:    "Shissar",
			Male:    "SHM",
			Female:  "SHF",
			Neutral: "SHN",
		},
		{
			ID:      218,
			Name:    "Fungal Fiend",
			Neutral: "FUG",
		},
		{
			ID:      219,
			Name:    "Vampire",
			Neutral: "VOL",
		},
		{
			ID:      220,
			Name:    "Stonegrabber",
			Neutral: "SGR",
		},
		{
			ID:      221,
			Name:    "Scarlet Cheetah",
			Neutral: "SCH",
		},
		{
			ID:      222,
			Name:    "Zelniak",
			Neutral: "ZEL",
		},
		{
			ID:      223,
			Name:    "Lightcrawler",
			Neutral: "LCR",
		},
		{
			ID:     224,
			Name:   "Shade",
			Male:   "SDM",
			Female: "SDF",
		},
		{
			ID:      225,
			Name:    "Sunflower",
			Neutral: "SNN",
		},
		{
			ID:      226,
			Name:    "Sun Revenant",
			Neutral: "SRV",
		},
		{
			ID:      227,
			Name:    "Shrieker",
			Neutral: "SHR",
		},
		{
			ID:      228,
			Name:    "Galorian",
			Neutral: "GAL",
		},
		{
			ID:      229,
			Name:    "Netherbian",
			Neutral: "NET",
		},
		{
			ID:      230,
			Name:    "Akheva",
			Male:    "AKM",
			Female:  "AKF",
			Neutral: "AKN",
		},
		{
			ID:      231,
			Name:    "Grieg Veneficus",
			Neutral: "SPR",
		},
		{
			ID:      232,
			Name:    "Sonic Wolf",
			Neutral: "SOW",
		},
		{
			ID:      233,
			Name:    "Ground Shaker",
			Male:    "GSM",
			Female:  "GSF",
			Neutral: "GSN",
		},
		{
			ID:      234,
			Name:    "Vah Shir Skeleton",
			Neutral: "KES",
		},
		{
			ID:      235,
			Name:    "Wretch",
			Neutral: "MUH",
		},
		{
			ID:      236,
			Name:    "Seru",
			Neutral: "SER",
		},
		{
			ID:      237,
			Name:    "Recuso",
			Male:    "REM",
			Female:  "REF",
			Neutral: "REN",
		},
		{
			ID:      238,
			Name:    "Vah Shir",
			Neutral: "VSK",
		},
		{
			ID:      239,
			Name:    "Guard",
			Neutral: "VSG",
		},
		{
			ID:      240,
			Name:    "Teleport Man",
			Male:    "TPM",
			Female:  "TPF",
			Neutral: "TPN",
		},
		{
			ID:      241,
			Name:    "Werewolf",
			Neutral: "LUJ",
		},
		{
			ID:      242,
			Name:    "Nymph",
			Neutral: "NYD",
		},
		{
			ID:      243,
			Name:    "Dryad",
			Neutral: "NYM",
		},
		{
			ID:      244,
			Name:    "Treant",
			Neutral: "TRN",
		},
		{
			ID:      245,
			Name:    "Fly",
			Neutral: "WRF",
		},
		{
			ID:      246,
			Name:    "Tarew Marr",
			Neutral: "TMR",
		},
		{
			ID:      247,
			Name:    "Solusek Ro",
			Neutral: "SRO",
		},
		{
			ID:      248,
			Name:    "Clockwork Golem",
			Neutral: "CLG",
		},
		{
			ID:      249,
			Name:    "Clockwork Brain",
			Neutral: "CLB",
		},
		{
			ID:      250,
			Name:    "Banshee",
			Neutral: "SKB",
		},
		{
			ID:      251,
			Name:    "Guard of Justice",
			Neutral: "GOJ",
		},
		{
			ID:      252,
			Name:    "Mini POM",
			Male:    "MINIPOM200",
			Female:  "MINIPOM200",
			Neutral: "MINIPOM200",
		},
		{
			ID:      253,
			Name:    "Diseased Fiend",
			Neutral: "DSB",
		},
		{
			ID:      254,
			Name:    "Solusek Ro Guard",
			Neutral: "SRG",
		},
		{
			ID:      255,
			Name:    "Bertoxxulous",
			Neutral: "BTX",
		},
		{
			ID:      256,
			Name:    "The Tribunal",
			Neutral: "TBU",
		},
		{
			ID:      257,
			Name:    "Terris Thule",
			Neutral: "TRT",
		},
		{
			ID:      258,
			Name:    "Vegerog",
			Neutral: "VEG",
		},
		{
			ID:      259,
			Name:    "Crocodile",
			Neutral: "CRO",
		},
		{
			ID:      260,
			Name:    "Bat",
			Neutral: "NBT",
		},
		{
			ID:      261,
			Name:    "Hraquis",
			Neutral: "SLG",
		},
		{
			ID:      262,
			Name:    "Tranquilion",
			Neutral: "TRQ",
		},
		{
			ID:      263,
			Name:    "Tin Soldier",
			Neutral: "TIN",
		},
		{
			ID:      264,
			Name:    "Nightmare Wraith",
			Neutral: "NMW",
		},
		{
			ID:      265,
			Name:    "Malarian",
			Neutral: "MAL",
		},
		{
			ID:      266,
			Name:    "Knight of Pestilence",
			Neutral: "KOP",
		},
		{
			ID:      267,
			Name:    "Lepertoloth",
			Neutral: "LEP",
		},
		{
			ID:      268,
			Name:    "Bubonian",
			Neutral: "BUB",
		},
		{
			ID:      269,
			Name:    "Bubonian Underling",
			Neutral: "BUU",
		},
		{
			ID:      270,
			Name:    "Pusling",
			Neutral: "PUS",
		},
		{
			ID:      271,
			Name:    "Water Mephit",
			Neutral: "WMP",
		},
		{
			ID:      272,
			Name:    "Stormrider",
			Neutral: "STR",
		},
		{
			ID:      273,
			Name:    "Junk Beast",
			Neutral: "JUB",
		},
		{
			ID:      274,
			Name:    "Broken Clockwork",
			Neutral: "BRC",
		},
		{
			ID:      275,
			Name:    "Giant Clockwork",
			Neutral: "GLC",
		},
		{
			ID:      276,
			Name:    "Clockwork Beetle",
			Neutral: "CWB",
		},
		{
			ID:      277,
			Name:    "Nightmare Goblin",
			Neutral: "NMG",
		},
		{
			ID:      278,
			Name:    "Karana",
			Neutral: "KAR",
		},
		{
			ID:      279,
			Name:    "Blood Raven",
			Neutral: "BRV",
		},
		{
			ID:      280,
			Name:    "Nightmare Gargoyle",
			Neutral: "GGL",
		},
		{
			ID:      281,
			Name:    "Mouth of Insanity",
			Neutral: "MOI",
		},
		{
			ID:      282,
			Name:    "Skeletal Horse",
			Neutral: "HSS",
		},
		{
			ID:      283,
			Name:    "Saryrn",
			Neutral: "SAR",
		},
		{
			ID:      284,
			Name:    "Fennin Ro",
			Neutral: "FEN",
		},
		{
			ID:      285,
			Name:    "Tormentor",
			Neutral: "TRW",
		},
		{
			ID:      286,
			Name:    "Soul Devourer",
			Neutral: "NPT",
		},
		{
			ID:      287,
			Name:    "Nightmare",
			Neutral: "NMH",
		},
		{
			ID:      288,
			Name:    "Rallos Zek",
			Neutral: "RAZ",
		},
		{
			ID:      289,
			Name:    "Vallon Zek",
			Neutral: "VAZ",
		},
		{
			ID:      290,
			Name:    "Tallon Zek",
			Neutral: "TAZ",
		},
		{
			ID:      291,
			Name:    "Air Mephit",
			Neutral: "AMP",
		},
		{
			ID:      292,
			Name:    "Earth Mephit",
			Neutral: "EMP",
		},
		{
			ID:      293,
			Name:    "Fire Mephit",
			Neutral: "FMP",
		},
		{
			ID:      294,
			Name:    "Nightmare Mephit",
			Neutral: "NMP",
		},
		{
			ID:      295,
			Name:    "Zebuxoruk",
			Neutral: "ZEB",
		},
		{
			ID:      296,
			Name:    "Mithaniel Marr",
			Neutral: "MAR",
		},
		{
			ID:      297,
			Name:    "Undead Knight",
			Neutral: "UDK",
		},
		{
			ID:      298,
			Name:    "The Rathe",
			Neutral: "RTH",
		},
		{
			ID:      299,
			Name:    "Xegony",
			Neutral: "XEG",
		},
		{
			ID:      300,
			Name:    "Fiend",
			Neutral: "GTD",
		},
		{
			ID:      301,
			Name:    "Test Object",
			Neutral: "ONT",
		},
		{
			ID:      302,
			Name:    "Crab",
			Neutral: "CRB",
		},
		{
			ID:      303,
			Name:    "Phoenix",
			Neutral: "PHX",
		},
		{
			ID:      304,
			Name:    "Dragon",
			Neutral: "TMT",
		},
		{
			ID:      305,
			Name:    "Bear",
			Neutral: "PBR",
		},
		{
			ID:      306,
			Name:    "Giant",
			Neutral: "STA",
		},
		{
			ID:      307,
			Name:    "Giant",
			Neutral: "SSA",
		},
		{
			ID:      308,
			Name:    "Giant",
			Neutral: "SKR",
		},
		{
			ID:      309,
			Name:    "Giant",
			Neutral: "SVO",
		},
		{
			ID:      310,
			Name:    "Giant",
			Neutral: "SMA",
		},
		{
			ID:      311,
			Name:    "Giant",
			Neutral: "STF",
		},
		{
			ID:      312,
			Name:    "Giant",
			Neutral: "SCE",
		},
		{
			ID:      313,
			Name:    "War Wraith",
			Neutral: "WRW",
		},
		{
			ID:      314,
			Name:    "Wrulon",
			Neutral: "WRU",
		},
		{
			ID:      315,
			Name:    "Kraken",
			Neutral: "KRK",
		},
		{
			ID:      316,
			Name:    "Poison Frog",
			Neutral: "PAF",
		},
		{
			ID:      317,
			Name:    "Nilborien",
			Neutral: "QZT",
		},
		{
			ID:      318,
			Name:    "Valorian",
			Neutral: "VAL",
		},
		{
			ID:      319,
			Name:    "War Boar",
			Neutral: "WRB",
		},
		{
			ID:      320,
			Name:    "Efreeti",
			Neutral: "EFE",
		},
		{
			ID:      321,
			Name:    "War Boar",
			Neutral: "WBU",
		},
		{
			ID:      322,
			Name:    "Valorian",
			Neutral: "BKN",
		},
		{
			ID:      323,
			Name:    "Animated Armor",
			Neutral: "AAM",
		},
		{
			ID:      324,
			Name:    "Undead Footman",
			Neutral: "UDF",
		},
		{
			ID:      325,
			Name:    "Rallos Zek Minion",
			Neutral: "RZM",
		},
		{
			ID:      326,
			Name:    "Arachnid",
			Neutral: "SPD",
		},
		{
			ID:      327,
			Name:    "Crystal Spider",
			Neutral: "SPL",
		},
		{
			ID:      328,
			Name:    "Zebuxoruk's Cage",
			Neutral: "ZBC",
		},
		{
			ID:      329,
			Name:    "BoT Portal",
			Neutral: "BTP",
		},
		{
			ID:     330,
			Name:   "Froglok",
			Male:   "FRM",
			Female: "FRF",
		},
		{
			ID:     331,
			Name:   "Troll",
			Male:   "TBM",
			Female: "TBF",
		},
		{
			ID:     332,
			Name:   "Troll",
			Male:   "FBM",
			Female: "FBF",
		},
		{
			ID:     333,
			Name:   "Troll",
			Male:   "TSM",
			Female: "TSF",
		},
		{
			ID:      334,
			Name:    "Ghost",
			Neutral: "SPB",
		},
		{
			ID:      335,
			Name:    "Pirate",
			Neutral: "TPB",
		},
		{
			ID:      336,
			Name:    "Pirate",
			Neutral: "TVP",
		},
		{
			ID:      337,
			Name:    "Pirate",
			Neutral: "TPO",
		},
		{
			ID:     338,
			Name:   "Pirate",
			Male:   "GPM",
			Female: "GPF",
		},
		{
			ID:     339,
			Name:   "Pirate",
			Male:   "DPM",
			Female: "DPF",
		},
		{
			ID:     340,
			Name:   "Pirate",
			Male:   "OPM",
			Female: "OPF",
		},
		{
			ID:     341,
			Name:   "Pirate",
			Male:   "HPM",
			Female: "HPF",
		},
		{
			ID:     342,
			Name:   "Pirate",
			Male:   "EPM",
			Female: "EPF",
		},
		{
			ID:      343,
			Name:    "Frog",
			Neutral: "RPF",
		},
		{
			ID:     344,
			Name:   "Troll Zombie",
			Male:   "TZM",
			Female: "TZF",
		},
		{
			ID:      345,
			Name:    "Luggald",
			Neutral: "LUG",
		},
		{
			ID:      346,
			Name:    "Luggald",
			Neutral: "LGA",
		},
		{
			ID:      347,
			Name:    "Luggalds",
			Neutral: "LGR",
		},
		{
			ID:      348,
			Name:    "Drogmore",
			Neutral: "FMT",
		},
		{
			ID:      349,
			Name:    "Froglok Skeleton",
			Neutral: "FSK",
		},
		{
			ID:      350,
			Name:    "Undead Froglok",
			Neutral: "FUD",
		},
		{
			ID:     351,
			Name:   "Knight of Hate",
			Male:   "IWM",
			Female: "IWF",
		},
		{
			ID:     352,
			Name:   "Arcanist of Hate",
			Male:   "IZM",
			Female: "IZF",
		},
		{
			ID:      353,
			Name:    "Veksar",
			Neutral: "VEK",
		},
		{
			ID:      354,
			Name:    "Veksar",
			Neutral: "GVK",
		},
		{
			ID:      355,
			Name:    "Veksar",
			Neutral: "BVK",
		},
		{
			ID:      356,
			Name:    "Chokidai",
			Neutral: "WOF",
		},
		{
			ID:      357,
			Name:    "Undead Chokidai",
			Neutral: "WUF",
		},
		{
			ID:      358,
			Name:    "Undead Veksar",
			Neutral: "UVK",
		},
		{
			ID:     359,
			Name:   "Vampire",
			Male:   "LMM",
			Female: "LMF",
		},
		{
			ID:     360,
			Name:   "Vampire",
			Male:   "MMM",
			Female: "MMF",
		},
		{
			ID:      361,
			Name:    "Rujarkian Orc",
			Neutral: "ROM",
		},
		{
			ID:      362,
			Name:    "Bone Golem",
			Neutral: "BGB",
		},
		{
			ID:      363,
			Name:    "Synarcana",
			Neutral: "SYN",
		},
		{
			ID:     364,
			Name:   "Sand Elf",
			Male:   "SEM",
			Female: "SEF",
		},
		{
			ID:      365,
			Name:    "Vampire",
			Neutral: "MMV",
		},
		{
			ID:      366,
			Name:    "Rujarkian Orc",
			Neutral: "ROE",
		},
		{
			ID:      367,
			Name:    "Skeleton",
			Neutral: "SKT",
		},
		{
			ID:      368,
			Name:    "Mummy",
			Neutral: "MMY",
		},
		{
			ID:      369,
			Name:    "Goblin",
			Neutral: "GBL",
		},
		{
			ID:      370,
			Name:    "Insect",
			Neutral: "NIN",
		},
		{
			ID:      371,
			Name:    "Froglok Ghost",
			Neutral: "FGH",
		},
		{
			ID:      372,
			Name:    "Dervish",
			Neutral: "DRV",
		},
		{
			ID:      373,
			Name:    "Shade",
			Neutral: "SDC",
		},
		{
			ID:      374,
			Name:    "Golem",
			Neutral: "GLM",
		},
		{
			ID:      375,
			Name:    "Evil Eye",
			Neutral: "EEY",
		},
		{
			ID:      376,
			Name:    "Box",
			Neutral: "BOX",
		},
		{
			ID:      377,
			Name:    "Barrel",
			Neutral: "BRL",
		},
		{
			ID:      378,
			Name:    "Chest",
			Neutral: "CST",
		},
		{
			ID:      379,
			Name:    "Vase",
			Neutral: "VAS",
		},
		{
			ID:      380,
			Name:    "Table",
			Neutral: "TBL",
		},
		{
			ID:      381,
			Name:    "Weapon Rack",
			Neutral: "RAK",
		},
		{
			ID:      382,
			Name:    "Coffin",
			Neutral: "CPT",
		},
		{
			ID:      383,
			Name:    "Bones",
			Neutral: "BON",
		},
		{
			ID:      384,
			Name:    "Jokester",
			Neutral: "JKR",
		},
		{
			ID:     385,
			Name:   "Nihil",
			Male:   "TNM",
			Female: "TNF",
		},
		{
			ID:     386,
			Name:   "Trusik",
			Male:   "TEM",
			Female: "TEF",
		},
		{
			ID:      387,
			Name:    "Stone Worker",
			Neutral: "TGL",
		},
		{
			ID:      388,
			Name:    "Hynid",
			Neutral: "TWF",
		},
		{
			ID:      389,
			Name:    "Turepta",
			Neutral: "TAC",
		},
		{
			ID:      390,
			Name:    "Cragbeast",
			Neutral: "TMB",
		},
		{
			ID:      391,
			Name:    "Stonemite",
			Neutral: "TTB",
		},
		{
			ID:      392,
			Name:    "Ukun",
			Neutral: "IWH",
		},
		{
			ID:      393,
			Name:    "Ixt",
			Neutral: "IEC",
		},
		{
			ID:      394,
			Name:    "Ikaav",
			Neutral: "ILA",
		},
		{
			ID:      395,
			Name:    "Aneuk",
			Neutral: "ICY",
		},
		{
			ID:      396,
			Name:    "Kyv",
			Neutral: "IHU",
		},
		{
			ID:      397,
			Name:    "Noc",
			Neutral: "ISB",
		},
		{
			ID:      398,
			Name:    "Ra`tuk",
			Neutral: "IBR",
		},
		{
			ID:      399,
			Name:    "Taneth",
			Neutral: "IFC",
		},
		{
			ID:      400,
			Name:    "Huvul",
			Neutral: "ILB",
		},
		{
			ID:      401,
			Name:    "Mutna",
			Neutral: "IWB",
		},
		{
			ID:      402,
			Name:    "Mastruq",
			Neutral: "ISE",
		},
		{
			ID:      403,
			Name:    "Taelosian",
			Neutral: "TLN",
		},
		{
			ID:      404,
			Name:    "Discord Ship",
			Neutral: "SHP",
		},
		{
			ID:      405,
			Name:    "Stone Worker",
			Neutral: "TGO",
		},
		{
			ID:      406,
			Name:    "Mata Muram",
			Neutral: "CLV",
		},
		{
			ID:      407,
			Name:    "Lightning Warrior",
			Neutral: "MUR",
		},
		{
			ID:      408,
			Name:    "Succubus",
			Neutral: "SCU",
		},
		{
			ID:      409,
			Name:    "Bazu",
			Neutral: "DSG",
		},
		{
			ID:      410,
			Name:    "Feran",
			Neutral: "FRA",
		},
		{
			ID:      411,
			Name:    "Pyrilen",
			Neutral: "SCU",
		},
		{
			ID:      412,
			Name:    "Chimera",
			Neutral: "CHM",
		},
		{
			ID:      413,
			Name:    "Dragorn",
			Neutral: "DDM",
		},
		{
			ID:      414,
			Name:    "Murkglider",
			Neutral: "DMA",
		},
		{
			ID:      415,
			Name:    "Rat",
			Neutral: "RTN",
		},
		{
			ID:      416,
			Name:    "Bat",
			Neutral: "BTN",
		},
		{
			ID:      417,
			Name:    "Gelidran",
			Neutral: "FRD",
		},
		{
			ID:      418,
			Name:    "Discordling",
			Neutral: "DSF",
		},
		{
			ID:      419,
			Name:    "Girplan",
			Neutral: "DDV",
		},
		{
			ID:      420,
			Name:    "Minotaur",
			Neutral: "MNT",
		},
		{
			ID:      421,
			Name:    "Dragorn Box",
			Neutral: "DBX",
		},
		{
			ID:      422,
			Name:    "Runed Orb",
			Neutral: "ROB",
		},
		{
			ID:      423,
			Name:    "Dragon Bones",
			Neutral: "DBP",
		},
		{
			ID:      424,
			Name:    "Muramite Armor Pile",
			Neutral: "MAP",
		},
		{
			ID:      425,
			Name:    "Crystal Shard",
			Neutral: "CRS",
		},
		{
			ID:      426,
			Name:    "Portal",
			Neutral: "PRT",
		},
		{
			ID:      427,
			Name:    "Coin Purse",
			Neutral: "CNP",
		},
		{
			ID:      428,
			Name:    "Rock Pile",
			Neutral: "RKP",
		},
		{
			ID:      429,
			Name:    "Murkglider Egg Sac",
			Neutral: "MES",
		},
		{
			ID:      430,
			Name:    "Drake",
			Neutral: "CDR",
		},
		{
			ID:      431,
			Name:    "Dervish",
			Neutral: "DVS",
		},
		{
			ID:      432,
			Name:    "Drake",
			Neutral: "DKE",
		},
		{
			ID:      433,
			Name:    "Goblin",
			Neutral: "GBN",
		},
		{
			ID:      434,
			Name:    "Kirin",
			Neutral: "KRN",
		},
		{
			ID:      435,
			Name:    "Dragon",
			Neutral: "LDR",
		},
		{
			ID:      436,
			Name:    "Basilisk",
			Neutral: "BAS",
		},
		{
			ID:      437,
			Name:    "Dragon",
			Neutral: "MDR",
		},
		{
			ID:      438,
			Name:    "Dragon",
			Neutral: "SDR",
		},
		{
			ID:      439,
			Name:    "Puma",
			Neutral: "PMA",
		},
		{
			ID:      440,
			Name:    "Spider",
			Neutral: "TAR",
		},
		{
			ID:      441,
			Name:    "Spider Queen",
			Neutral: "SPQ",
		},
		{
			ID:      442,
			Name:    "Animated Statue",
			Neutral: "ANS",
		},
		{
			ID:      445,
			Name:    "Dragon Egg",
			Neutral: "DRE",
		},
		{
			ID:      446,
			Name:    "Dragon Statue",
			Neutral: "DRS",
		},
		{
			ID:      447,
			Name:    "Lava Rock",
			Neutral: "LVR",
		},
		{
			ID:      448,
			Name:    "Animated Statue",
			Neutral: "ASM",
		},
		{
			ID:      449,
			Name:    "Spider Egg Sack",
			Neutral: "SEG",
		},
		{
			ID:      450,
			Name:    "Lava Spider",
			Neutral: "LSP",
		},
		{
			ID:      451,
			Name:    "Lava Spider Queen",
			Neutral: "LSQ",
		},
		{
			ID:      452,
			Name:    "Dragon",
			Neutral: "SHD",
		},
		{
			ID:      453,
			Name:    "Giant",
			Neutral: "FGT",
		},
		{
			ID:      454,
			Name:    "Werewolf",
			Neutral: "WWF",
		},
		{
			ID:      455,
			Name:    "Kobold",
			Neutral: "KBD",
		},
		{
			ID:      456,
			Name:    "Sporali",
			Neutral: "FNG",
		},
		{
			ID:      457,
			Name:    "Gnomework",
			Neutral: "CWG",
		},
		{
			ID:      458,
			Name:    "Orc",
			Neutral: "ORK",
		},
		{
			ID:      459,
			Name:    "Corathus",
			Neutral: "CRH",
		},
		{
			ID:      460,
			Name:    "Coral",
			Neutral: "CRL",
		},
		{
			ID:     461,
			Name:   "Drachnid",
			Male:   "DCM",
			Female: "DCF",
		},
		{
			ID:      462,
			Name:    "Drachnid Cocoon",
			Neutral: "DRC",
		},
		{
			ID:      463,
			Name:    "Fungus Patch",
			Neutral: "FGP",
		},
		{
			ID:      464,
			Name:    "Gargoyle",
			Neutral: "GGY",
		},
		{
			ID:      465,
			Name:    "Witheran",
			Neutral: "KOR",
		},
		{
			ID:      466,
			Name:    "Dark Lord",
			Neutral: "MYG",
		},
		{
			ID:      467,
			Name:    "Shiliskin",
			Neutral: "SHL",
		},
		{
			ID:      468,
			Name:    "Snake",
			Neutral: "SNK",
		},
		{
			ID:      469,
			Name:    "Evil Eye",
			Neutral: "EVE",
		},
		{
			ID:      470,
			Name:    "Minotaur",
			Neutral: "MNR",
		},
		{
			ID:     471,
			Name:   "Zombie",
			Male:   "ZMM",
			Female: "ZMF",
		},
		{
			ID:      472,
			Name:    "Clockwork Boar",
			Neutral: "CWR",
		},
		{
			ID:      473,
			Name:    "Fairy",
			Neutral: "FRY",
		},
		{
			ID:      474,
			Name:    "Witheran",
			Neutral: "KRB",
		},
		{
			ID:      475,
			Name:    "Air Elemental",
			Neutral: "AIE",
		},
		{
			ID:      476,
			Name:    "Earth Elemental",
			Neutral: "EAE",
		},
		{
			ID:      477,
			Name:    "Fire Elemental",
			Neutral: "FIE",
		},
		{
			ID:      478,
			Name:    "Water Elemental",
			Neutral: "WAE",
		},
		{
			ID:      479,
			Name:    "Alligator",
			Neutral: "ALR",
		},
		{
			ID:      480,
			Name:    "Bear",
			Neutral: "BAR",
		},
		{
			ID:      481,
			Name:    "Scaled Wolf",
			Neutral: "SCW",
		},
		{
			ID:      482,
			Name:    "Wolf",
			Neutral: "WLF",
		},
		{
			ID:      483,
			Name:    "Spirit Wolf",
			Neutral: "SPW",
		},
		{
			ID:      484,
			Name:    "Skeleton",
			Neutral: "SKL",
		},
		{
			ID:      485,
			Name:    "Spectre",
			Neutral: "SPT",
		},
		{
			ID:      486,
			Name:    "Bolvirk",
			Neutral: "BLV",
		},
		{
			ID:     487,
			Name:   "Banshee",
			Female: "BSE",
		},
		{
			ID:     488,
			Name:   "Banshee",
			Female: "BSG",
		},
		{
			ID:     489,
			Name:   "Elddar",
			Male:   "EEM",
			Female: "EEF",
		},
		{
			ID:      490,
			Name:    "Forest Giant",
			Neutral: "GFO",
		},
		{
			ID:      491,
			Name:    "Bone Golem",
			Neutral: "GLB",
		},
		{
			ID:      492,
			Name:    "Horse",
			Neutral: "HRS",
		},
		{
			ID:      493,
			Name:    "Pegasus",
			Neutral: "PGS",
		},
		{
			ID:      494,
			Name:    "Shambling Mound",
			Neutral: "SMD",
		},
		{
			ID:      495,
			Name:    "Scrykin",
			Neutral: "SRN",
		},
		{
			ID:      496,
			Name:    "Treant",
			Neutral: "TRA",
		},
		{
			ID:     497,
			Name:   "Vampire",
			Male:   "VAM",
			Female: "VAF",
		},
		{
			ID:     498,
			Name:   "Ayonae Ro",
			Female: "ARO",
		},
		{
			ID:     499,
			Name:   "Sullon Zek",
			Female: "SZK",
		},
		{
			ID:      500,
			Name:    "Banner",
			Neutral: "BNR",
		},
		{
			ID:      501,
			Name:    "Flag",
			Neutral: "FLG",
		},
		{
			ID:      502,
			Name:    "Rowboat",
			Neutral: "ROW",
		},
		{
			ID:      503,
			Name:    "Bear Trap",
			Neutral: "T00",
		},
		{
			ID:      504,
			Name:    "Clockwork Bomb",
			Neutral: "T01",
		},
		{
			ID:      505,
			Name:    "Dynamite Keg",
			Neutral: "T02",
		},
		{
			ID:      506,
			Name:    "Pressure Plate",
			Neutral: "T03",
		},
		{
			ID:      507,
			Name:    "Puffer Spore",
			Neutral: "T04",
		},
		{
			ID:      508,
			Name:    "Stone Ring",
			Neutral: "T05",
		},
		{
			ID:      509,
			Name:    "Root Tentacle",
			Neutral: "T06",
		},
		{
			ID:      510,
			Name:    "Runic Symbol",
			Neutral: "T07",
		},
		{
			ID:      511,
			Name:    "Saltpetter Bomb",
			Neutral: "T08",
		},
		{
			ID:      512,
			Name:    "Floating Skull",
			Neutral: "T09",
		},
		{
			ID:      513,
			Name:    "Spike Trap",
			Neutral: "T10",
		},
		{
			ID:      514,
			Name:    "Totem",
			Neutral: "T11",
		},
		{
			ID:      515,
			Name:    "Web",
			Neutral: "T12",
		},
		{
			ID:      516,
			Name:    "Wicker Basket",
			Neutral: "T13",
		},
		{
			ID:      517,
			Name:    "Nightmare/Unicorn",
			Neutral: "UNM",
		},
		{
			ID:      518,
			Name:    "Horse",
			Neutral: "HRS",
		},
		{
			ID:      519,
			Name:    "Nightmare/Unicorn",
			Neutral: "UNM",
		},
		{
			ID:      520,
			Name:    "Bixie",
			Neutral: "BXI",
		},
		{
			ID:      521,
			Name:    "Centaur",
			Neutral: "CNT",
		},
		{
			ID:     522,
			Name:   "Drakkin",
			Male:   "DKM",
			Female: "DKF",
		},
		{
			ID:      523,
			Name:    "Giant",
			Neutral: "GFR",
		},
		{
			ID:      524,
			Name:    "Gnoll",
			Neutral: "GNL",
		},
		{
			ID:      525,
			Name:    "Griffin",
			Neutral: "GRN",
		},
		{
			ID:      526,
			Name:    "Giant Shade",
			Neutral: "GFS",
		},
		{
			ID:      527,
			Name:    "Harpy",
			Neutral: "HRP",
		},
		{
			ID:      528,
			Name:    "Mammoth",
			Neutral: "MTH",
		},
		{
			ID:      529,
			Name:    "Satyr",
			Neutral: "SAT",
		},
		{
			ID:      530,
			Name:    "Dragon",
			Neutral: "DRG",
		},
		{
			ID:      531,
			Name:    "Dragon",
			Neutral: "DRN",
		},
		{
			ID:      532,
			Name:    "Dyn'Leth",
			Neutral: "DYN",
		},
		{
			ID:      533,
			Name:    "Boat",
			Neutral: "SHI",
		},
		{
			ID:      534,
			Name:    "Weapon Rack",
			Neutral: "I00",
		},
		{
			ID:      535,
			Name:    "Armor Rack",
			Neutral: "I01",
		},
		{
			ID:      536,
			Name:    "Honey Pot",
			Neutral: "I02",
		},
		{
			ID:      537,
			Name:    "Jum Jum Bucket",
			Neutral: "I03",
		},
		{
			ID:      538,
			Name:    "Toolbox",
			Neutral: "I04",
		},
		{
			ID:      539,
			Name:    "Stone Jug",
			Neutral: "I05",
		},
		{
			ID:      540,
			Name:    "Small Plant",
			Neutral: "I06",
		},
		{
			ID:      541,
			Name:    "Medium Plant",
			Neutral: "I07",
		},
		{
			ID:      542,
			Name:    "Tall Plant",
			Neutral: "I08",
		},
		{
			ID:      543,
			Name:    "Wine Cask",
			Neutral: "I09",
		},
		{
			ID:      544,
			Name:    "Elven Boat",
			Neutral: "B01",
		},
		{
			ID:      545,
			Name:    "Gnomish Boat",
			Neutral: "B02",
		},
		{
			ID:      546,
			Name:    "Barrel Barge Ship",
			Neutral: "B03",
		},
		{
			ID:      547,
			Name:    "Goo",
			Neutral: "GUL",
		},
		{
			ID:      548,
			Name:    "Goo",
			Neutral: "GUM",
		},
		{
			ID:      549,
			Name:    "Goo",
			Neutral: "GUS",
		},
		{
			ID:      550,
			Name:    "Merchant Ship",
			Neutral: "B04",
		},
		{
			ID:      551,
			Name:    "Pirate Ship",
			Neutral: "B05",
		},
		{
			ID:      552,
			Name:    "Ghost Ship",
			Neutral: "B06",
		},
		{
			ID:      553,
			Name:    "Banner",
			Neutral: "G00",
		},
		{
			ID:      554,
			Name:    "Banner",
			Neutral: "G01",
		},
		{
			ID:      555,
			Name:    "Banner",
			Neutral: "G02",
		},
		{
			ID:      556,
			Name:    "Banner",
			Neutral: "G03",
		},
		{
			ID:      557,
			Name:    "Banner",
			Neutral: "G04",
		},
		{
			ID:      558,
			Name:    "Aviak",
			Neutral: "AVK",
		},
		{
			ID:      559,
			Name:    "Beetle",
			Neutral: "BTL",
		},
		{
			ID:      560,
			Name:    "Gorilla",
			Neutral: "GRL",
		},
		{
			ID:      561,
			Name:    "Kedge",
			Neutral: "KDG",
		},
		{
			ID:     562,
			Name:   "Kerran",
			Male:   "KRM",
			Female: "KRF",
		},
		{
			ID:      563,
			Name:    "Shissar",
			Neutral: "SHS",
		},
		{
			ID:      564,
			Name:    "Siren",
			Neutral: "SIN",
		},
		{
			ID:      565,
			Name:    "Sphinx",
			Neutral: "SPX",
		},
		{
			ID:     566,
			Name:   "Human",
			Male:   "HNM",
			Female: "HNF",
		},
		{
			ID:      567,
			Name:    "Campfire",
			Neutral: "I10",
		},
		{
			ID:     568,
			Name:   "Brownie",
			Male:   "BNM",
			Female: "BNF",
		},
		{
			ID:      569,
			Name:    "Dragon",
			Neutral: "DRP",
		},
		{
			ID:      570,
			Name:    "Exoskeleton",
			Neutral: "EXO",
		},
		{
			ID:      571,
			Name:    "Ghoul",
			Neutral: "GHO",
		},
		{
			ID:      572,
			Name:    "Clockwork Guardian",
			Neutral: "GUA",
		},
		{
			ID:      573,
			Name:    "Mantrap",
			Neutral: "MTP",
		},
		{
			ID:      574,
			Name:    "Minotaur",
			Neutral: "MTR",
		},
		{
			ID:      575,
			Name:    "Scarecrow",
			Neutral: "SCC",
		},
		{
			ID:      576,
			Name:    "Shade",
			Neutral: "SHE",
		},
		{
			ID:      577,
			Name:    "Rotocopter",
			Neutral: "SWC",
		},
		{
			ID:      578,
			Name:    "Tentacle Terror",
			Neutral: "TNT",
		},
		{
			ID:      579,
			Name:    "Wereorc",
			Neutral: "WOK",
		},
		{
			ID:      580,
			Name:    "Worg",
			Neutral: "WOR",
		},
		{
			ID:      581,
			Name:    "Wyvern",
			Neutral: "WYR",
		},
		{
			ID:      582,
			Name:    "Chimera",
			Neutral: "MCH",
		},
		{
			ID:      583,
			Name:    "Kirin",
			Neutral: "MKI",
		},
		{
			ID:      584,
			Name:    "Puma",
			Neutral: "MPU",
		},
		{
			ID:      585,
			Name:    "Boulder",
			Neutral: "I11",
		},
		{
			ID:      586,
			Name:    "Banner",
			Neutral: "G05",
		},
		{
			ID:     587,
			Name:   "Elven Ghost",
			Male:   "XEM",
			Female: "XEF",
		},
		{
			ID:     588,
			Name:   "Human Ghost",
			Male:   "XHM",
			Female: "XHF",
		},
		{
			ID:      589,
			Name:    "Chest",
			Neutral: "I12",
		},
		{
			ID:      590,
			Name:    "Chest",
			Neutral: "I13",
		},
		{
			ID:      591,
			Name:    "Crystal",
			Neutral: "I14",
		},
		{
			ID:      592,
			Name:    "Coffin",
			Neutral: "I15",
		},
		{
			ID:      593,
			Name:    "Guardian CPU",
			Neutral: "I16",
		},
		{
			ID:      594,
			Name:    "Worg",
			Neutral: "MWO",
		},
		{
			ID:      595,
			Name:    "Mansion",
			Neutral: "OBJ_BLIMP",
		},
		{
			ID:      596,
			Name:    "Floating Island",
			Neutral: "OBP__MELDRATH",
		},
		{
			ID:      597,
			Name:    "Cragslither",
			Neutral: "MCS",
		},
		{
			ID:      598,
			Name:    "Wrulon",
			Neutral: "MWR",
		},
		{
			ID:      599,
			Name:    "Spell Particle 1",
			Neutral: "S01",
		},
		{
			ID:     600,
			Name:   "Invisible Man of Zomm",
			Male:   "IVM",
			Female: "IVF",
		},
		{
			ID:      601,
			Name:    "Robocopter of Zomm",
			Neutral: "SWC",
		},
		{
			ID:      602,
			Name:    "Burynai",
			Neutral: "BUR",
		},
		{
			ID:      603,
			Name:    "Frog",
			Neutral: "FGG",
		},
		{
			ID:      604,
			Name:    "Dracolich",
			Neutral: "DRL",
		},
		{
			ID:      605,
			Name:    "Iksar Ghost",
			Neutral: "XIM",
		},
		{
			ID:      606,
			Name:    "Iksar Skeleton",
			Neutral: "SKI",
		},
		{
			ID:      607,
			Name:    "Mephit",
			Neutral: "MPH",
		},
		{
			ID:      608,
			Name:    "Muddite",
			Neutral: "MUD",
		},
		{
			ID:      609,
			Name:    "Raptor",
			Neutral: "RPT",
		},
		{
			ID:      610,
			Name:    "Sarnak",
			Neutral: "SRK",
		},
		{
			ID:      611,
			Name:    "Scorpion",
			Neutral: "SCO",
		},
		{
			ID:      612,
			Name:    "Tsetsian",
			Neutral: "TSE",
		},
		{
			ID:      613,
			Name:    "Wurm",
			Neutral: "WRM",
		},
		{
			ID:      614,
			Name:    "Nekhon",
			Neutral: "BAL",
		},
		{
			ID:      615,
			Name:    "Hydra Crystal",
			Neutral: "HYC",
		},
		{
			ID:      616,
			Name:    "Crystal Sphere",
			Neutral: "CRY",
		},
		{
			ID:      617,
			Name:    "Gnoll",
			Neutral: "GND",
		},
		{
			ID:      618,
			Name:    "Sokokar",
			Neutral: "SOK",
		},
		{
			ID:      619,
			Name:    "Stone Pylon",
			Neutral: "PYS",
		},
		{
			ID:      620,
			Name:    "Demon Vulture",
			Neutral: "DVL",
		},
		{
			ID:      621,
			Name:    "Wagon",
			Neutral: "I17",
		},
		{
			ID:      622,
			Name:    "God of Discord",
			Neutral: "GOD",
		},
		{
			ID:      623,
			Name:    "Feran Mount",
			Neutral: "MFR",
		},
		{
			ID:     624,
			Name:   "Ogre NPC - Male",
			Male:   "ONM",
			Female: "ONF",
		},
		{
			ID:      625,
			Name:    "Sokokar Mount",
			Neutral: "MSO",
		},
		{
			ID:      626,
			Name:    "Giant (Rallosian mats)",
			Neutral: "GRA",
		},
		{
			ID:      627,
			Name:    "Sokokar (w saddle)",
			Neutral: "MSO",
		},
		{
			ID:      628,
			Name:    "10th Anniversary Banner",
			Neutral: "BNX",
		},
		{
			ID:      629,
			Name:    "10th Anniversary Cake",
			Neutral: "CAK",
		},
		{
			ID:      630,
			Name:    "Wine Cask",
			Neutral: "I18",
		},
		{
			ID:      631,
			Name:    "Hydra Mount",
			Neutral: "MHY",
		},
		{
			ID:      632,
			Name:    "Hydra NPC",
			Neutral: "HYD",
		},
		{
			ID:      633,
			Name:    "Wedding Flowers",
			Neutral: "I19",
		},
		{
			ID:      634,
			Name:    "Wedding Arbor",
			Neutral: "I20",
		},
		{
			ID:      635,
			Name:    "Wedding Altar",
			Neutral: "I21",
		},
		{
			ID:      636,
			Name:    "Powder Keg",
			Neutral: "I22",
		},
		{
			ID:      637,
			Name:    "Apexus",
			Neutral: "APX",
		},
		{
			ID:      638,
			Name:    "Bellikos",
			Neutral: "BEL",
		},
		{
			ID:      639,
			Name:    "Brell's First Creation",
			Neutral: "BFC",
		},
		{
			ID:      640,
			Name:    "Brell",
			Neutral: "BRE",
		},
		{
			ID:      641,
			Name:    "Crystalskin Ambuloid",
			Neutral: "CAM",
		},
		{
			ID:      642,
			Name:    "Cliknar Queen",
			Neutral: "CLQ",
		},
		{
			ID:      643,
			Name:    "Cliknar Soldier",
			Neutral: "CLS",
		},
		{
			ID:      644,
			Name:    "Cliknar Worker",
			Neutral: "CLW",
		},
		{
			ID:     645,
			Name:   "Coldain",
			Male:   "CDM",
			Female: "CDF",
		},
		{
			ID:      647,
			Name:    "Crystalskin Sessiloid",
			Neutral: "CSE",
		},
		{
			ID:      648,
			Name:    "Genari",
			Neutral: "GEN",
		},
		{
			ID:      649,
			Name:    "Gigyn",
			Neutral: "GIG",
		},
		{
			ID:      650,
			Name:    "Greken - Young Adult",
			Neutral: "GYA",
		},
		{
			ID:      651,
			Name:    "Greken - Young",
			Neutral: "GYO",
		},
		{
			ID:      652,
			Name:    "Cliknar Mount",
			Neutral: "MCL",
		},
		{
			ID:      653,
			Name:    "Telmira",
			Neutral: "TEL",
		},
		{
			ID:      654,
			Name:    "Spider Mount",
			Neutral: "MTA",
		},
		{
			ID:      655,
			Name:    "Bear Mount",
			Neutral: "MBR",
		},
		{
			ID:      656,
			Name:    "Rat Mount",
			Neutral: "MCR",
		},
		{
			ID:      657,
			Name:    "Sessiloid Mount",
			Neutral: "MSD",
		},
		{
			ID:      658,
			Name:    "Morell Thule",
			Neutral: "LTH",
		},
		{
			ID:      659,
			Name:    "Marionette",
			Neutral: "MRT",
		},
		{
			ID:      660,
			Name:    "Book Dervish",
			Neutral: "BKD",
		},
		{
			ID:      661,
			Name:    "Topiary Lion",
			Neutral: "TPL",
		},
		{
			ID:      662,
			Name:    "Rotdog",
			Neutral: "RDG",
		},
		{
			ID:      663,
			Name:    "Amygdalan",
			Neutral: "AMY",
		},
		{
			ID:      664,
			Name:    "Sandman",
			Neutral: "SND",
		},
		{
			ID:      665,
			Name:    "Grandfather Clock",
			Neutral: "GFC",
		},
		{
			ID:      666,
			Name:    "Gingerbread Man",
			Neutral: "GBM",
		},
		{
			ID:     667,
			Name:   "Royal Guard",
			Male:   "BFR",
			Female: "BFF",
		},
		{
			ID:      668,
			Name:    "Rabbit",
			Neutral: "BNY",
		},
		{
			ID:      669,
			Name:    "Blind Dreamer",
			Neutral: "BDR",
		},
		{
			ID:      670,
			Name:    "Cazic Thule",
			Neutral: "CTH",
		},
		{
			ID:      671,
			Name:    "Topiary Lion Mount",
			Neutral: "MTL",
		},
		{
			ID:      672,
			Name:    "Rot Dog Mount",
			Neutral: "MRD",
		},
		{
			ID:      673,
			Name:    "Goral Mount",
			Neutral: "MGL",
		},
		{
			ID:      674,
			Name:    "Selyrah Mount",
			Neutral: "MSL",
		},
		{
			ID:      675,
			Name:    "Sclera Mount",
			Neutral: "MSC",
		},
		{
			ID:      676,
			Name:    "Braxi Mount",
			Neutral: "MBX",
		},
		{
			ID:      677,
			Name:    "Kangon Mount",
			Neutral: "MKG",
		},
		{
			ID:   678,
			Name: "Erudite",
			Male: "ERU",
		},
		{
			ID:      679,
			Name:    "Wurm Mount",
			Neutral: "MWM",
		},
		{
			ID:      680,
			Name:    "Raptor Mount",
			Neutral: "MRP",
		},
		{
			ID:      681,
			Name:    "Invisible Man",
			Neutral: "INV",
		},
		{
			ID:      682,
			Name:    "Whirligig",
			Neutral: "MWI",
		},
		{
			ID:      683,
			Name:    "Gnomish Balloon",
			Neutral: "MBL",
		},
		{
			ID:      684,
			Name:    "Gnomish Rocket Pack",
			Neutral: "MRK",
		},
		{
			ID:      685,
			Name:    "Gnomish Hovering Transport",
			Neutral: "MHB",
		},
		{
			ID:      686,
			Name:    "Selyrah",
			Neutral: "SEY",
		},
		{
			ID:      687,
			Name:    "Goral",
			Neutral: "G}1",
		},
		{
			ID:      688,
			Name:    "Braxi",
			Neutral: "BRX",
		},
		{
			ID:      689,
			Name:    "Kangon",
			Neutral: "KNG",
		},
		{
			ID:      690,
			Name:    "Invisible Man",
			Neutral: "I23",
		},
		{
			ID:      691,
			Name:    "Floating Tower",
			Neutral: "B07",
		},
		{
			ID:      692,
			Name:    "Explosive Cart",
			Neutral: "B08",
		},
		{
			ID:      693,
			Name:    "Blimp Ship",
			Neutral: "B09",
		},
		{
			ID:      694,
			Name:    "Tumbleweed",
			Neutral: "I24",
		},
		{
			ID:      695,
			Name:    "Alaran",
			Neutral: "ALA",
		},
		{
			ID:      696,
			Name:    "Swinetor",
			Neutral: "SWI",
		},
		{
			ID:      697,
			Name:    "Triumvirate",
			Neutral: "TRG",
		},
		{
			ID:      698,
			Name:    "Hadal",
			Neutral: "HDL",
		},
		{
			ID:      699,
			Name:    "Hovering Platform",
			Neutral: "B10",
		},
		{
			ID:      700,
			Name:    "Parasitic Scavenger",
			Neutral: "PSC",
		},
		{
			ID:      701,
			Name:    "Grendlaen",
			Neutral: "GRD",
		},
		{
			ID:      702,
			Name:    "Ship in a Bottle",
			Neutral: "I25",
		},
		{
			ID:      703,
			Name:    "Alaran Sentry Stone",
			Neutral: "I26",
		},
		{
			ID:      704,
			Name:    "Dervish",
			Neutral: "SDV",
		},
		{
			ID:      705,
			Name:    "Regeneration Pool",
			Neutral: "I27",
		},
		{
			ID:      706,
			Name:    "Teleportation Stand",
			Neutral: "I28",
		},
		{
			ID:      707,
			Name:    "Relic Case",
			Neutral: "I29",
		},
		{
			ID:      708,
			Name:    "Alaran Ghost",
			Neutral: "ALG",
		},
		{
			ID:      709,
			Name:    "Skystrider",
			Neutral: "MPG",
		},
		{
			ID:      710,
			Name:    "Water Spout",
			Neutral: "I30",
		},
		{
			ID:      711,
			Name:    "Aviak Pull Along",
			Neutral: "I31",
		},
		{
			ID:      712,
			Name:    "Gelatinous Cube",
			Neutral: "GCB",
		},
		{
			ID:      713,
			Name:    "Cat",
			Neutral: "CAT",
		},
		{
			ID:      714,
			Name:    "Elk Head",
			Neutral: "I32",
		},
		{
			ID:      715,
			Name:    "Holgresh",
			Neutral: "HLG",
		},
		{
			ID:      716,
			Name:    "Beetle",
			Neutral: "BTS",
		},
		{
			ID:      717,
			Name:    "Vine Maw",
			Neutral: "VNM",
		},
		{
			ID:      718,
			Name:    "Ratman",
			Neutral: "CHT",
		},
		{
			ID:      719,
			Name:    "Fallen Knight",
			Neutral: "FKN",
		},
		{
			ID:      720,
			Name:    "Flying Carpet",
			Neutral: "MCP",
		},
		{
			ID:      721,
			Name:    "Carrier Hand",
			Neutral: "MRH",
		},
		{
			ID:     722,
			Name:   "Akheva",
			Male:   "AHM",
			Female: "AHF",
		},
		{
			ID:   723,
			Name: "Servant of Shadow",
			Male: "SOS",
		},
		{
			ID:     724,
			Name:   "Luclin",
			Female: "LUC",
		},
		{
			ID:      725,
			Name:    "Xaric the Unspoken",
			Neutral: "AXA",
		},
		{
			ID:      726,
			Name:    "Dervish (Ver. 5)",
			Neutral: "HDV",
		},
		{
			ID:      727,
			Name:    "Dervish (Ver. 6)",
			Neutral: "DV6",
		},
		{
			ID:      728,
			Name:    "God - Luclin (Ver. 2)",
			Neutral: "LU2",
		},
		{
			ID:      729,
			Name:    "God - Luclin (Ver. 3)",
			Neutral: "LU3",
		},
		{
			ID:      730,
			Name:    "Orb",
			Neutral: "ORB",
		},
		{
			ID:      731,
			Name:    "God - Luclin (Ver. 4)",
			Neutral: "LU4",
		},
		{
			ID:      732,
			Name:    "Pegasus",
			Neutral: "PG3",
		},
		{
			ID:      2253,
			Name:    "(2253-PPOINT)",
			Male:    "PPOINT",
			Female:  "PPOINT",
			Neutral: "PPOINT",
		},
		{
			ID:      2254,
			Name:    "(2254-PPOINT)",
			Male:    "PPOINT",
			Female:  "PPOINT",
			Neutral: "PPOINT",
		},
		{
			ID:      2255,
			Name:    "(2255-PPOINT)",
			Male:    "PPOINT",
			Female:  "PPOINT",
			Neutral: "PPOINT",
		},
		{
			ID:      2256,
			Name:    "(2256-PPOINT)",
			Male:    "PPOINT",
			Female:  "PPOINT",
			Neutral: "PPOINT",
		},
		{
			ID:      2257,
			Name:    "(2257-PPOINT)",
			Male:    "PPOINT",
			Female:  "PPOINT",
			Neutral: "PPOINT",
		},
		{
			ID:      2258,
			Name:    "(2258-PPOINT)",
			Male:    "PPOINT",
			Female:  "PPOINT",
			Neutral: "PPOINT",
		},
		{
			ID:      2259,
			Name:    "(2259-ARROW)",
			Male:    "ARROW",
			Female:  "ARROW",
			Neutral: "ARROW",
		},
	}
}
