// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/page.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Page struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Order                string   `protobuf:"bytes,5,opt,name=order,proto3" json:"order,omitempty"`
	IsDescending         bool     `protobuf:"varint,6,opt,name=is_descending,json=isDescending,proto3" json:"is_descending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_c965c0ea1b49dc4e, []int{0}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Page) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Page) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Page) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

func (m *Page) GetIsDescending() bool {
	if m != nil {
		return m.IsDescending
	}
	return false
}

func init() {
	proto.RegisterType((*Page)(nil), "pb.Page")
}

func init() { proto.RegisterFile("pb/page.proto", fileDescriptor_c965c0ea1b49dc4e) }

var fileDescriptor_c965c0ea1b49dc4e = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xd2, 0x2f,
	0x48, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x6a, 0x65,
	0xe4, 0x62, 0x09, 0x48, 0x4c, 0x4f, 0x15, 0x12, 0xe3, 0x62, 0xcb, 0x4f, 0x4b, 0x2b, 0x4e, 0x2d,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf2, 0x84, 0x44, 0xb8, 0x58, 0x73, 0x32, 0x73,
	0x33, 0x4b, 0x24, 0x98, 0xc0, 0xc2, 0x10, 0x0e, 0x48, 0xb4, 0x24, 0xbf, 0x24, 0x31, 0x47, 0x82,
	0x19, 0x22, 0x0a, 0xe6, 0x80, 0x44, 0xf3, 0x8b, 0x52, 0x52, 0x8b, 0x24, 0x58, 0x15, 0x18, 0x35,
	0x38, 0x83, 0x20, 0x1c, 0x21, 0x65, 0x2e, 0xde, 0xcc, 0xe2, 0xf8, 0x94, 0xd4, 0xe2, 0xe4, 0xd4,
	0xbc, 0x94, 0xcc, 0xbc, 0x74, 0x09, 0x36, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x9e, 0xcc, 0x62, 0x17,
	0xb8, 0x58, 0x12, 0x1b, 0xd8, 0x49, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x59, 0x52,
	0x88, 0xa3, 0x00, 0x00, 0x00,
}
