// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/race.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Race struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Bit                  int64    `protobuf:"varint,4,opt,name=bit,proto3" json:"bit,omitempty"`
	Male                 string   `protobuf:"bytes,5,opt,name=male,proto3" json:"male,omitempty"`
	Female               string   `protobuf:"bytes,6,opt,name=female,proto3" json:"female,omitempty"`
	Neutral              string   `protobuf:"bytes,7,opt,name=neutral,proto3" json:"neutral,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Race) Reset()         { *m = Race{} }
func (m *Race) String() string { return proto.CompactTextString(m) }
func (*Race) ProtoMessage()    {}
func (*Race) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0a3eedf5a4907b8, []int{0}
}

func (m *Race) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Race.Unmarshal(m, b)
}
func (m *Race) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Race.Marshal(b, m, deterministic)
}
func (m *Race) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Race.Merge(m, src)
}
func (m *Race) XXX_Size() int {
	return xxx_messageInfo_Race.Size(m)
}
func (m *Race) XXX_DiscardUnknown() {
	xxx_messageInfo_Race.DiscardUnknown(m)
}

var xxx_messageInfo_Race proto.InternalMessageInfo

func (m *Race) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Race) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Race) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Race) GetBit() int64 {
	if m != nil {
		return m.Bit
	}
	return 0
}

func (m *Race) GetMale() string {
	if m != nil {
		return m.Male
	}
	return ""
}

func (m *Race) GetFemale() string {
	if m != nil {
		return m.Female
	}
	return ""
}

func (m *Race) GetNeutral() string {
	if m != nil {
		return m.Neutral
	}
	return ""
}

func init() {
	proto.RegisterType((*Race)(nil), "pb.Race")
}

func init() { proto.RegisterFile("pb/race.proto", fileDescriptor_f0a3eedf5a4907b8) }

var fileDescriptor_f0a3eedf5a4907b8 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0x41, 0x0a, 0xc2, 0x30,
	0x10, 0x45, 0x49, 0x5a, 0x5b, 0x1c, 0x50, 0x64, 0x16, 0x32, 0xcb, 0xe2, 0xaa, 0x2b, 0x5d, 0x78,
	0x93, 0xdc, 0x20, 0x49, 0x47, 0x08, 0xb4, 0x49, 0x08, 0xf1, 0x2a, 0x9e, 0x57, 0x32, 0xd5, 0xdd,
	0xfb, 0x6f, 0xfe, 0xc0, 0x87, 0x53, 0x76, 0x8f, 0x62, 0x3d, 0xdf, 0x73, 0x49, 0x35, 0xa1, 0xce,
	0xee, 0xf6, 0x51, 0xd0, 0x1b, 0xeb, 0x19, 0xcf, 0xa0, 0xc3, 0x42, 0x6a, 0x52, 0x73, 0x67, 0x74,
	0x58, 0x10, 0xa1, 0x8f, 0x76, 0x63, 0xd2, 0x93, 0x9a, 0x8f, 0x46, 0xb8, 0xb9, 0xe0, 0x53, 0xa4,
	0x6e, 0x77, 0x8d, 0xf1, 0x02, 0x9d, 0x0b, 0x95, 0x7a, 0x79, 0x6c, 0xd8, 0x5a, 0x9b, 0x5d, 0x99,
	0x0e, 0x7b, 0xab, 0x31, 0x5e, 0x61, 0x78, 0xb1, 0xd8, 0x41, 0xec, 0x2f, 0x21, 0xc1, 0x18, 0xf9,
	0x5d, 0x8b, 0x5d, 0x69, 0x94, 0xc3, 0x3f, 0xba, 0x41, 0x36, 0x3e, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x58, 0x5c, 0x0d, 0x67, 0xb4, 0x00, 0x00, 0x00,
}
